// Code generated by schemaf codegen. DO NOT EDIT.
// Regenerate with: ./schemaf.sh codegen
package tests

import (
	"net/http/httptest"
	"os/exec"
	"testing"

	schemafapi "github.com/flocko-motion/schemaf/api"
	"rankedb/api"
)

func newTSTestServer(t *testing.T) *httptest.Server {
	t.Helper()
	schemafapi.Reset()
	api.Provider()
	srv := httptest.NewServer(schemafapi.NewMux())
	t.Cleanup(srv.Close)
	return srv
}

func runTSTest(t *testing.T, funcName string, srv *httptest.Server) {
	t.Helper()
	cmd := exec.Command("npx", "tsx", "runner.gen.ts", funcName, srv.URL)
	out, err := cmd.CombinedOutput()
	if len(out) > 0 {
		t.Log(string(out))
	}
	if err != nil {
		t.Fatalf("TS test %q failed", funcName)
	}
}

func TestCreateAndGetSourceNode(t *testing.T) {
	srv := newTSTestServer(t)
	runTSTest(t, "testCreateAndGetSourceNode", srv)
}

func TestL0Idempotency(t *testing.T) {
	srv := newTSTestServer(t)
	runTSTest(t, "testL0Idempotency", srv)
}

func TestL1RequiresProvenance(t *testing.T) {
	srv := newTSTestServer(t)
	runTSTest(t, "testL1RequiresProvenance", srv)
}

func TestCreateL1WithProvenance(t *testing.T) {
	srv := newTSTestServer(t)
	runTSTest(t, "testCreateL1WithProvenance", srv)
}

func TestListNodes(t *testing.T) {
	srv := newTSTestServer(t)
	runTSTest(t, "testListNodes", srv)
}

func TestCreateRelation(t *testing.T) {
	srv := newTSTestServer(t)
	runTSTest(t, "testCreateRelation", srv)
}

func TestAmbiguousRelation(t *testing.T) {
	srv := newTSTestServer(t)
	runTSTest(t, "testAmbiguousRelation", srv)
}

