// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: edges.sql

package db

import (
	"context"
	"database/sql"
)

const getEdge = `-- name: GetEdge :one
SELECT id, source_node_id, target_node_id, type, confidence, run_id, created_at FROM edges WHERE id = $1
`

func (q *Queries) GetEdge(ctx context.Context, id string) (Edge, error) {
	row := q.db.QueryRowContext(ctx, getEdge, id)
	var i Edge
	err := row.Scan(
		&i.ID,
		&i.SourceNodeID,
		&i.TargetNodeID,
		&i.Type,
		&i.Confidence,
		&i.RunID,
		&i.CreatedAt,
	)
	return i, err
}

const getEdgesByRun = `-- name: GetEdgesByRun :many
SELECT id, source_node_id, target_node_id, type, confidence, run_id, created_at FROM edges WHERE run_id = $1 ORDER BY created_at
`

func (q *Queries) GetEdgesByRun(ctx context.Context, runID sql.NullString) ([]Edge, error) {
	rows, err := q.db.QueryContext(ctx, getEdgesByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Edge
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.ID,
			&i.SourceNodeID,
			&i.TargetNodeID,
			&i.Type,
			&i.Confidence,
			&i.RunID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEdgesBySource = `-- name: GetEdgesBySource :many
SELECT id, source_node_id, target_node_id, type, confidence, run_id, created_at FROM edges WHERE source_node_id = $1 ORDER BY created_at
`

func (q *Queries) GetEdgesBySource(ctx context.Context, sourceNodeID string) ([]Edge, error) {
	rows, err := q.db.QueryContext(ctx, getEdgesBySource, sourceNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Edge
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.ID,
			&i.SourceNodeID,
			&i.TargetNodeID,
			&i.Type,
			&i.Confidence,
			&i.RunID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEdgesBySourceAndType = `-- name: GetEdgesBySourceAndType :many
SELECT id, source_node_id, target_node_id, type, confidence, run_id, created_at FROM edges WHERE source_node_id = $1 AND type = $2 ORDER BY created_at
`

type GetEdgesBySourceAndTypeParams struct {
	SourceNodeID string `json:"source_node_id"`
	Type         string `json:"type"`
}

func (q *Queries) GetEdgesBySourceAndType(ctx context.Context, arg GetEdgesBySourceAndTypeParams) ([]Edge, error) {
	rows, err := q.db.QueryContext(ctx, getEdgesBySourceAndType, arg.SourceNodeID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Edge
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.ID,
			&i.SourceNodeID,
			&i.TargetNodeID,
			&i.Type,
			&i.Confidence,
			&i.RunID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEdgesByTarget = `-- name: GetEdgesByTarget :many
SELECT id, source_node_id, target_node_id, type, confidence, run_id, created_at FROM edges WHERE target_node_id = $1 ORDER BY created_at
`

func (q *Queries) GetEdgesByTarget(ctx context.Context, targetNodeID string) ([]Edge, error) {
	rows, err := q.db.QueryContext(ctx, getEdgesByTarget, targetNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Edge
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.ID,
			&i.SourceNodeID,
			&i.TargetNodeID,
			&i.Type,
			&i.Confidence,
			&i.RunID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEdgesByTargetAndType = `-- name: GetEdgesByTargetAndType :many
SELECT id, source_node_id, target_node_id, type, confidence, run_id, created_at FROM edges WHERE target_node_id = $1 AND type = $2 ORDER BY created_at
`

type GetEdgesByTargetAndTypeParams struct {
	TargetNodeID string `json:"target_node_id"`
	Type         string `json:"type"`
}

func (q *Queries) GetEdgesByTargetAndType(ctx context.Context, arg GetEdgesByTargetAndTypeParams) ([]Edge, error) {
	rows, err := q.db.QueryContext(ctx, getEdgesByTargetAndType, arg.TargetNodeID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Edge
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.ID,
			&i.SourceNodeID,
			&i.TargetNodeID,
			&i.Type,
			&i.Confidence,
			&i.RunID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEdge = `-- name: InsertEdge :exec
INSERT INTO edges (id, source_node_id, target_node_id, type, confidence, run_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertEdgeParams struct {
	ID           string          `json:"id"`
	SourceNodeID string          `json:"source_node_id"`
	TargetNodeID string          `json:"target_node_id"`
	Type         string          `json:"type"`
	Confidence   sql.NullFloat64 `json:"confidence"`
	RunID        sql.NullString  `json:"run_id"`
}

func (q *Queries) InsertEdge(ctx context.Context, arg InsertEdgeParams) error {
	_, err := q.db.ExecContext(ctx, insertEdge,
		arg.ID,
		arg.SourceNodeID,
		arg.TargetNodeID,
		arg.Type,
		arg.Confidence,
		arg.RunID,
	)
	return err
}
