// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: edges.sql

package db

import (
	"context"
)

const getProvenanceByRun = `-- name: GetProvenanceByRun :many
SELECT id, source_id, target_id, run_id, created_at FROM edges_provenance WHERE run_id = $1 ORDER BY created_at
`

func (q *Queries) GetProvenanceByRun(ctx context.Context, runID string) ([]EdgesProvenance, error) {
	rows, err := q.db.QueryContext(ctx, getProvenanceByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EdgesProvenance
	for rows.Next() {
		var i EdgesProvenance
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.RunID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProvenanceInputs = `-- name: GetProvenanceInputs :many
SELECT id, source_id, target_id, run_id, created_at FROM edges_provenance WHERE target_id = $1 ORDER BY created_at
`

func (q *Queries) GetProvenanceInputs(ctx context.Context, targetID string) ([]EdgesProvenance, error) {
	rows, err := q.db.QueryContext(ctx, getProvenanceInputs, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EdgesProvenance
	for rows.Next() {
		var i EdgesProvenance
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.RunID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProvenanceOutputs = `-- name: GetProvenanceOutputs :many
SELECT id, source_id, target_id, run_id, created_at FROM edges_provenance WHERE source_id = $1 ORDER BY created_at
`

func (q *Queries) GetProvenanceOutputs(ctx context.Context, sourceID string) ([]EdgesProvenance, error) {
	rows, err := q.db.QueryContext(ctx, getProvenanceOutputs, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EdgesProvenance
	for rows.Next() {
		var i EdgesProvenance
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.RunID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSemanticEdge = `-- name: GetSemanticEdge :one
SELECT id, relation_id, head_id, tail_id, created_at FROM edges_semantic WHERE relation_id = $1
`

func (q *Queries) GetSemanticEdge(ctx context.Context, relationID string) (EdgesSemantic, error) {
	row := q.db.QueryRowContext(ctx, getSemanticEdge, relationID)
	var i EdgesSemantic
	err := row.Scan(
		&i.ID,
		&i.RelationID,
		&i.HeadID,
		&i.TailID,
		&i.CreatedAt,
	)
	return i, err
}

const getSemanticEdgesByHead = `-- name: GetSemanticEdgesByHead :many
SELECT id, relation_id, head_id, tail_id, created_at FROM edges_semantic WHERE head_id = $1
`

func (q *Queries) GetSemanticEdgesByHead(ctx context.Context, headID string) ([]EdgesSemantic, error) {
	rows, err := q.db.QueryContext(ctx, getSemanticEdgesByHead, headID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EdgesSemantic
	for rows.Next() {
		var i EdgesSemantic
		if err := rows.Scan(
			&i.ID,
			&i.RelationID,
			&i.HeadID,
			&i.TailID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSemanticEdgesByTail = `-- name: GetSemanticEdgesByTail :many
SELECT id, relation_id, head_id, tail_id, created_at FROM edges_semantic WHERE tail_id = $1
`

func (q *Queries) GetSemanticEdgesByTail(ctx context.Context, tailID string) ([]EdgesSemantic, error) {
	rows, err := q.db.QueryContext(ctx, getSemanticEdgesByTail, tailID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EdgesSemantic
	for rows.Next() {
		var i EdgesSemantic
		if err := rows.Scan(
			&i.ID,
			&i.RelationID,
			&i.HeadID,
			&i.TailID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertProvenanceEdge = `-- name: InsertProvenanceEdge :exec
INSERT INTO edges_provenance (source_id, target_id, run_id)
VALUES ($1, $2, $3)
ON CONFLICT (source_id, target_id, run_id) DO NOTHING
`

type InsertProvenanceEdgeParams struct {
	SourceID string `json:"source_id"`
	TargetID string `json:"target_id"`
	RunID    string `json:"run_id"`
}

func (q *Queries) InsertProvenanceEdge(ctx context.Context, arg InsertProvenanceEdgeParams) error {
	_, err := q.db.ExecContext(ctx, insertProvenanceEdge, arg.SourceID, arg.TargetID, arg.RunID)
	return err
}

const insertSemanticEdge = `-- name: InsertSemanticEdge :exec
INSERT INTO edges_semantic (relation_id, head_id, tail_id)
VALUES ($1, $2, $3)
ON CONFLICT (relation_id) DO NOTHING
`

type InsertSemanticEdgeParams struct {
	RelationID string `json:"relation_id"`
	HeadID     string `json:"head_id"`
	TailID     string `json:"tail_id"`
}

func (q *Queries) InsertSemanticEdge(ctx context.Context, arg InsertSemanticEdgeParams) error {
	_, err := q.db.ExecContext(ctx, insertSemanticEdge, arg.RelationID, arg.HeadID, arg.TailID)
	return err
}
