// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type EdgesProvenance struct {
	ID        uuid.UUID `json:"id"`
	SourceID  string    `json:"source_id"`
	TargetID  string    `json:"target_id"`
	RunID     string    `json:"run_id"`
	CreatedAt time.Time `json:"created_at"`
}

type EdgesSemantic struct {
	ID         uuid.UUID `json:"id"`
	RelationID string    `json:"relation_id"`
	HeadID     string    `json:"head_id"`
	TailID     string    `json:"tail_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type Node struct {
	ID                    string          `json:"id"`
	Level                 int16           `json:"level"`
	ContentType           string          `json:"content_type"`
	Encoding              string          `json:"encoding"`
	ContentSha256         string          `json:"content_sha256"`
	ContentLen            int64           `json:"content_len"`
	ContentCached         sql.NullString  `json:"content_cached"`
	CreatedAt             time.Time       `json:"created_at"`
	ArtifactCreatedAt     sql.NullTime    `json:"artifact_created_at"`
	ArtifactCreatedAtBlur sql.NullString  `json:"artifact_created_at_blur"`
	Origin                sql.NullString  `json:"origin"`
	OriginalName          sql.NullString  `json:"original_name"`
	ValidFrom             sql.NullTime    `json:"valid_from"`
	ValidFromBlur         sql.NullString  `json:"valid_from_blur"`
	ValidUntil            sql.NullTime    `json:"valid_until"`
	ValidUntilBlur        sql.NullString  `json:"valid_until_blur"`
	Confidence            sql.NullFloat64 `json:"confidence"`
}
