// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nodes.sql

package db

import (
	"context"
	"database/sql"
)

const getNode = `-- name: GetNode :one
SELECT id, level, content_type, encoding, content_sha256, content_len, content_cached, created_at, artifact_created_at, artifact_created_at_blur, origin, original_name, valid_from, valid_from_blur, valid_until, valid_until_blur, confidence FROM nodes WHERE id = $1
`

func (q *Queries) GetNode(ctx context.Context, id string) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Level,
		&i.ContentType,
		&i.Encoding,
		&i.ContentSha256,
		&i.ContentLen,
		&i.ContentCached,
		&i.CreatedAt,
		&i.ArtifactCreatedAt,
		&i.ArtifactCreatedAtBlur,
		&i.Origin,
		&i.OriginalName,
		&i.ValidFrom,
		&i.ValidFromBlur,
		&i.ValidUntil,
		&i.ValidUntilBlur,
		&i.Confidence,
	)
	return i, err
}

const insertNode = `-- name: InsertNode :exec
INSERT INTO nodes (
    id, level, content_type, encoding,
    content_sha256, content_len, content_cached,
    artifact_created_at, artifact_created_at_blur, origin, original_name,
    valid_from, valid_from_blur, valid_until, valid_until_blur, confidence
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10, $11,
    $12, $13, $14, $15, $16
)
`

type InsertNodeParams struct {
	ID                    string          `json:"id"`
	Level                 int16           `json:"level"`
	ContentType           string          `json:"content_type"`
	Encoding              string          `json:"encoding"`
	ContentSha256         string          `json:"content_sha256"`
	ContentLen            int64           `json:"content_len"`
	ContentCached         sql.NullString  `json:"content_cached"`
	ArtifactCreatedAt     sql.NullTime    `json:"artifact_created_at"`
	ArtifactCreatedAtBlur sql.NullString  `json:"artifact_created_at_blur"`
	Origin                sql.NullString  `json:"origin"`
	OriginalName          sql.NullString  `json:"original_name"`
	ValidFrom             sql.NullTime    `json:"valid_from"`
	ValidFromBlur         sql.NullString  `json:"valid_from_blur"`
	ValidUntil            sql.NullTime    `json:"valid_until"`
	ValidUntilBlur        sql.NullString  `json:"valid_until_blur"`
	Confidence            sql.NullFloat64 `json:"confidence"`
}

func (q *Queries) InsertNode(ctx context.Context, arg InsertNodeParams) error {
	_, err := q.db.ExecContext(ctx, insertNode,
		arg.ID,
		arg.Level,
		arg.ContentType,
		arg.Encoding,
		arg.ContentSha256,
		arg.ContentLen,
		arg.ContentCached,
		arg.ArtifactCreatedAt,
		arg.ArtifactCreatedAtBlur,
		arg.Origin,
		arg.OriginalName,
		arg.ValidFrom,
		arg.ValidFromBlur,
		arg.ValidUntil,
		arg.ValidUntilBlur,
		arg.Confidence,
	)
	return err
}

const listNodesByContentType = `-- name: ListNodesByContentType :many
SELECT id, level, content_type, encoding, content_sha256, content_len, content_cached, created_at, artifact_created_at, artifact_created_at_blur, origin, original_name, valid_from, valid_from_blur, valid_until, valid_until_blur, confidence FROM nodes WHERE content_type = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListNodesByContentTypeParams struct {
	ContentType string `json:"content_type"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) ListNodesByContentType(ctx context.Context, arg ListNodesByContentTypeParams) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listNodesByContentType, arg.ContentType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.ContentType,
			&i.Encoding,
			&i.ContentSha256,
			&i.ContentLen,
			&i.ContentCached,
			&i.CreatedAt,
			&i.ArtifactCreatedAt,
			&i.ArtifactCreatedAtBlur,
			&i.Origin,
			&i.OriginalName,
			&i.ValidFrom,
			&i.ValidFromBlur,
			&i.ValidUntil,
			&i.ValidUntilBlur,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByLevel = `-- name: ListNodesByLevel :many
SELECT id, level, content_type, encoding, content_sha256, content_len, content_cached, created_at, artifact_created_at, artifact_created_at_blur, origin, original_name, valid_from, valid_from_blur, valid_until, valid_until_blur, confidence FROM nodes WHERE level = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListNodesByLevelParams struct {
	Level  int16 `json:"level"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListNodesByLevel(ctx context.Context, arg ListNodesByLevelParams) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listNodesByLevel, arg.Level, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.ContentType,
			&i.Encoding,
			&i.ContentSha256,
			&i.ContentLen,
			&i.ContentCached,
			&i.CreatedAt,
			&i.ArtifactCreatedAt,
			&i.ArtifactCreatedAtBlur,
			&i.Origin,
			&i.OriginalName,
			&i.ValidFrom,
			&i.ValidFromBlur,
			&i.ValidUntil,
			&i.ValidUntilBlur,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nodeExistsBySha256 = `-- name: NodeExistsBySha256 :one
SELECT id FROM nodes WHERE level = 0 AND content_sha256 = $1 LIMIT 1
`

func (q *Queries) NodeExistsBySha256(ctx context.Context, contentSha256 string) (string, error) {
	row := q.db.QueryRowContext(ctx, nodeExistsBySha256, contentSha256)
	var id string
	err := row.Scan(&id)
	return id, err
}
