// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package db

import (
	"context"
)

const getRun = `-- name: GetRun :one
SELECT id, worker_config_id, created_at FROM runs WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id string) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i Run
	err := row.Scan(&i.ID, &i.WorkerConfigID, &i.CreatedAt)
	return i, err
}

const insertRun = `-- name: InsertRun :exec
INSERT INTO runs (id, worker_config_id) VALUES ($1, $2)
`

type InsertRunParams struct {
	ID             string `json:"id"`
	WorkerConfigID string `json:"worker_config_id"`
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) error {
	_, err := q.db.ExecContext(ctx, insertRun, arg.ID, arg.WorkerConfigID)
	return err
}
