// Package apiclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apiclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// AdmitUserReq defines model for AdmitUserReq.
type AdmitUserReq struct {
	Subject string `json:"subject"`
	Tenant  string `json:"tenant"`
}

// AdmitUserResp defines model for AdmitUserResp.
type AdmitUserResp struct {
	Subject string `json:"subject"`
	Tenant  string `json:"tenant"`
}

// BranchResp defines model for BranchResp.
type BranchResp struct {
	Contributor string `json:"contributor"`
	Head        string `json:"head"`
	History     int    `json:"history"`
	Name        string `json:"name"`
	Time        string `json:"time"`
}

// BranchSummary defines model for BranchSummary.
type BranchSummary struct {
	Head string `json:"head"`
	Name string `json:"name"`
}

// ClaimView defines model for ClaimView.
type ClaimView struct {
	Canonical   string     `json:"canonical"`
	ContentHash string     `json:"content_hash"`
	Contributor string     `json:"contributor"`
	CreatedAt   string     `json:"created_at"`
	Edges       []EdgeView `json:"edges"`
	Encoding    string     `json:"encoding"`
	Id          string     `json:"id"`
	Size        int        `json:"size"`
	Type        string     `json:"type"`
}

// EdgeView defines model for EdgeView.
type EdgeView struct {
	Direction string `json:"direction"`
	Reference string `json:"reference"`
	Type      string `json:"type"`
}

// GetArchiveResp defines model for GetArchiveResp.
type GetArchiveResp struct {
	Current string `json:"current"`
	Ra      string `json:"ra"`
	Target  string `json:"target"`
	Tenant  string `json:"tenant"`
	Title   string `json:"title"`
}

// GrantRoleReq defines model for GrantRoleReq.
type GrantRoleReq struct {
	Ra      string `json:"ra"`
	Role    string `json:"role"`
	Subject string `json:"subject"`
	Tenant  string `json:"tenant"`
}

// GrantRoleResp defines model for GrantRoleResp.
type GrantRoleResp struct {
	Ra      string `json:"ra"`
	Role    string `json:"role"`
	Subject string `json:"subject"`
}

// ListBranchesResp defines model for ListBranchesResp.
type ListBranchesResp struct {
	Branches []BranchSummary `json:"branches"`
}

// ListSubjectsResp defines model for ListSubjectsResp.
type ListSubjectsResp struct {
	Subjects []SubjectView `json:"subjects"`
}

// ListTenantUsersResp defines model for ListTenantUsersResp.
type ListTenantUsersResp struct {
	Users []TenantUser `json:"users"`
}

// PatchArchiveReq defines model for PatchArchiveReq.
type PatchArchiveReq struct {
	Ra     string `json:"ra"`
	Target string `json:"target"`
	Tenant string `json:"tenant"`
}

// RoleEntry defines model for RoleEntry.
type RoleEntry struct {
	Ra   string `json:"ra"`
	Role string `json:"role"`
}

// SetUserDisabledReq defines model for SetUserDisabledReq.
type SetUserDisabledReq struct {
	Disabled bool   `json:"disabled"`
	Subject  string `json:"subject"`
}

// SubjectView defines model for SubjectView.
type SubjectView struct {
	Disabled bool   `json:"disabled"`
	Id       string `json:"id"`
}

// TenantUser defines model for TenantUser.
type TenantUser struct {
	Roles   []RoleEntry `json:"roles"`
	Subject string      `json:"subject"`
}

// VerificationResp defines model for VerificationResp.
type VerificationResp struct {
	Error string `json:"error"`
	Valid bool   `json:"valid"`
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// PatchApiArchivesTenantRaJSONRequestBody defines body for PatchApiArchivesTenantRa for application/json ContentType.
type PatchApiArchivesTenantRaJSONRequestBody = PatchArchiveReq

// PostApiTenantsTenantUsersJSONRequestBody defines body for PostApiTenantsTenantUsers for application/json ContentType.
type PostApiTenantsTenantUsersJSONRequestBody = AdmitUserReq

// PostApiTenantsTenantUsersSubjectGrantsJSONRequestBody defines body for PostApiTenantsTenantUsersSubjectGrants for application/json ContentType.
type PostApiTenantsTenantUsersSubjectGrantsJSONRequestBody = GrantRoleReq

// PatchApiUsersSubjectJSONRequestBody defines body for PatchApiUsersSubject for application/json ContentType.
type PatchApiUsersSubjectJSONRequestBody = SetUserDisabledReq

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetApiArchivesTenantRa request
	GetApiArchivesTenantRa(ctx context.Context, tenant string, ra string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchApiArchivesTenantRaWithBody request with any body
	PatchApiArchivesTenantRaWithBody(ctx context.Context, tenant string, ra string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PatchApiArchivesTenantRa(ctx context.Context, tenant string, ra string, body PatchApiArchivesTenantRaJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiArchivesTenantRaBranches request
	GetApiArchivesTenantRaBranches(ctx context.Context, tenant string, ra string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiArchivesTenantRaBranchesName request
	GetApiArchivesTenantRaBranchesName(ctx context.Context, tenant string, ra string, name string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiArchivesTenantRaBranchesNameVerification request
	GetApiArchivesTenantRaBranchesNameVerification(ctx context.Context, tenant string, ra string, name string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiArchivesTenantRaClaimsId request
	GetApiArchivesTenantRaClaimsId(ctx context.Context, tenant string, ra string, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiArchivesTenantRaGql request
	PostApiArchivesTenantRaGql(ctx context.Context, tenant string, ra string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiTenantsTenantUsers request
	GetApiTenantsTenantUsers(ctx context.Context, tenant string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiTenantsTenantUsersWithBody request with any body
	PostApiTenantsTenantUsersWithBody(ctx context.Context, tenant string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiTenantsTenantUsers(ctx context.Context, tenant string, body PostApiTenantsTenantUsersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteApiTenantsTenantUsersSubjectGrants request
	DeleteApiTenantsTenantUsersSubjectGrants(ctx context.Context, tenant string, subject string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiTenantsTenantUsersSubjectGrantsWithBody request with any body
	PostApiTenantsTenantUsersSubjectGrantsWithBody(ctx context.Context, tenant string, subject string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiTenantsTenantUsersSubjectGrants(ctx context.Context, tenant string, subject string, body PostApiTenantsTenantUsersSubjectGrantsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiUsers request
	GetApiUsers(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchApiUsersSubjectWithBody request with any body
	PatchApiUsersSubjectWithBody(ctx context.Context, subject string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PatchApiUsersSubject(ctx context.Context, subject string, body PatchApiUsersSubjectJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetApiArchivesTenantRa(ctx context.Context, tenant string, ra string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiArchivesTenantRaRequest(c.Server, tenant, ra)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchApiArchivesTenantRaWithBody(ctx context.Context, tenant string, ra string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchApiArchivesTenantRaRequestWithBody(c.Server, tenant, ra, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchApiArchivesTenantRa(ctx context.Context, tenant string, ra string, body PatchApiArchivesTenantRaJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchApiArchivesTenantRaRequest(c.Server, tenant, ra, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiArchivesTenantRaBranches(ctx context.Context, tenant string, ra string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiArchivesTenantRaBranchesRequest(c.Server, tenant, ra)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiArchivesTenantRaBranchesName(ctx context.Context, tenant string, ra string, name string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiArchivesTenantRaBranchesNameRequest(c.Server, tenant, ra, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiArchivesTenantRaBranchesNameVerification(ctx context.Context, tenant string, ra string, name string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiArchivesTenantRaBranchesNameVerificationRequest(c.Server, tenant, ra, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiArchivesTenantRaClaimsId(ctx context.Context, tenant string, ra string, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiArchivesTenantRaClaimsIdRequest(c.Server, tenant, ra, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiArchivesTenantRaGql(ctx context.Context, tenant string, ra string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiArchivesTenantRaGqlRequest(c.Server, tenant, ra)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiTenantsTenantUsers(ctx context.Context, tenant string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiTenantsTenantUsersRequest(c.Server, tenant)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiTenantsTenantUsersWithBody(ctx context.Context, tenant string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiTenantsTenantUsersRequestWithBody(c.Server, tenant, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiTenantsTenantUsers(ctx context.Context, tenant string, body PostApiTenantsTenantUsersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiTenantsTenantUsersRequest(c.Server, tenant, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteApiTenantsTenantUsersSubjectGrants(ctx context.Context, tenant string, subject string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteApiTenantsTenantUsersSubjectGrantsRequest(c.Server, tenant, subject)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiTenantsTenantUsersSubjectGrantsWithBody(ctx context.Context, tenant string, subject string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiTenantsTenantUsersSubjectGrantsRequestWithBody(c.Server, tenant, subject, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiTenantsTenantUsersSubjectGrants(ctx context.Context, tenant string, subject string, body PostApiTenantsTenantUsersSubjectGrantsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiTenantsTenantUsersSubjectGrantsRequest(c.Server, tenant, subject, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiUsers(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiUsersRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchApiUsersSubjectWithBody(ctx context.Context, subject string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchApiUsersSubjectRequestWithBody(c.Server, subject, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchApiUsersSubject(ctx context.Context, subject string, body PatchApiUsersSubjectJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchApiUsersSubjectRequest(c.Server, subject, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetApiArchivesTenantRaRequest generates requests for GetApiArchivesTenantRa
func NewGetApiArchivesTenantRaRequest(server string, tenant string, ra string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "tenant", tenant, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "ra", ra, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/archives/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchApiArchivesTenantRaRequest calls the generic PatchApiArchivesTenantRa builder with application/json body
func NewPatchApiArchivesTenantRaRequest(server string, tenant string, ra string, body PatchApiArchivesTenantRaJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchApiArchivesTenantRaRequestWithBody(server, tenant, ra, "application/json", bodyReader)
}

// NewPatchApiArchivesTenantRaRequestWithBody generates requests for PatchApiArchivesTenantRa with any type of body
func NewPatchApiArchivesTenantRaRequestWithBody(server string, tenant string, ra string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "tenant", tenant, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "ra", ra, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/archives/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPatch, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiArchivesTenantRaBranchesRequest generates requests for GetApiArchivesTenantRaBranches
func NewGetApiArchivesTenantRaBranchesRequest(server string, tenant string, ra string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "tenant", tenant, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "ra", ra, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/archives/%s/%s/branches", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiArchivesTenantRaBranchesNameRequest generates requests for GetApiArchivesTenantRaBranchesName
func NewGetApiArchivesTenantRaBranchesNameRequest(server string, tenant string, ra string, name string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "tenant", tenant, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "ra", ra, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/archives/%s/%s/branches/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiArchivesTenantRaBranchesNameVerificationRequest generates requests for GetApiArchivesTenantRaBranchesNameVerification
func NewGetApiArchivesTenantRaBranchesNameVerificationRequest(server string, tenant string, ra string, name string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "tenant", tenant, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "ra", ra, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/archives/%s/%s/branches/%s/verification", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiArchivesTenantRaClaimsIdRequest generates requests for GetApiArchivesTenantRaClaimsId
func NewGetApiArchivesTenantRaClaimsIdRequest(server string, tenant string, ra string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "tenant", tenant, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "ra", ra, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/archives/%s/%s/claims/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiArchivesTenantRaGqlRequest generates requests for PostApiArchivesTenantRaGql
func NewPostApiArchivesTenantRaGqlRequest(server string, tenant string, ra string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "tenant", tenant, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "ra", ra, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/archives/%s/%s/gql", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiTenantsTenantUsersRequest generates requests for GetApiTenantsTenantUsers
func NewGetApiTenantsTenantUsersRequest(server string, tenant string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "tenant", tenant, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/tenants/%s/users", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiTenantsTenantUsersRequest calls the generic PostApiTenantsTenantUsers builder with application/json body
func NewPostApiTenantsTenantUsersRequest(server string, tenant string, body PostApiTenantsTenantUsersJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiTenantsTenantUsersRequestWithBody(server, tenant, "application/json", bodyReader)
}

// NewPostApiTenantsTenantUsersRequestWithBody generates requests for PostApiTenantsTenantUsers with any type of body
func NewPostApiTenantsTenantUsersRequestWithBody(server string, tenant string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "tenant", tenant, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/tenants/%s/users", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteApiTenantsTenantUsersSubjectGrantsRequest generates requests for DeleteApiTenantsTenantUsersSubjectGrants
func NewDeleteApiTenantsTenantUsersSubjectGrantsRequest(server string, tenant string, subject string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "tenant", tenant, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "subject", subject, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/tenants/%s/users/%s/grants", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiTenantsTenantUsersSubjectGrantsRequest calls the generic PostApiTenantsTenantUsersSubjectGrants builder with application/json body
func NewPostApiTenantsTenantUsersSubjectGrantsRequest(server string, tenant string, subject string, body PostApiTenantsTenantUsersSubjectGrantsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiTenantsTenantUsersSubjectGrantsRequestWithBody(server, tenant, subject, "application/json", bodyReader)
}

// NewPostApiTenantsTenantUsersSubjectGrantsRequestWithBody generates requests for PostApiTenantsTenantUsersSubjectGrants with any type of body
func NewPostApiTenantsTenantUsersSubjectGrantsRequestWithBody(server string, tenant string, subject string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "tenant", tenant, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "subject", subject, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/tenants/%s/users/%s/grants", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiUsersRequest generates requests for GetApiUsers
func NewGetApiUsersRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/users")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchApiUsersSubjectRequest calls the generic PatchApiUsersSubject builder with application/json body
func NewPatchApiUsersSubjectRequest(server string, subject string, body PatchApiUsersSubjectJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchApiUsersSubjectRequestWithBody(server, subject, "application/json", bodyReader)
}

// NewPatchApiUsersSubjectRequestWithBody generates requests for PatchApiUsersSubject with any type of body
func NewPatchApiUsersSubjectRequestWithBody(server string, subject string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "subject", subject, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/users/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPatch, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetApiArchivesTenantRaWithResponse request
	GetApiArchivesTenantRaWithResponse(ctx context.Context, tenant string, ra string, reqEditors ...RequestEditorFn) (*GetApiArchivesTenantRaResponse, error)

	// PatchApiArchivesTenantRaWithBodyWithResponse request with any body
	PatchApiArchivesTenantRaWithBodyWithResponse(ctx context.Context, tenant string, ra string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchApiArchivesTenantRaResponse, error)

	PatchApiArchivesTenantRaWithResponse(ctx context.Context, tenant string, ra string, body PatchApiArchivesTenantRaJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchApiArchivesTenantRaResponse, error)

	// GetApiArchivesTenantRaBranchesWithResponse request
	GetApiArchivesTenantRaBranchesWithResponse(ctx context.Context, tenant string, ra string, reqEditors ...RequestEditorFn) (*GetApiArchivesTenantRaBranchesResponse, error)

	// GetApiArchivesTenantRaBranchesNameWithResponse request
	GetApiArchivesTenantRaBranchesNameWithResponse(ctx context.Context, tenant string, ra string, name string, reqEditors ...RequestEditorFn) (*GetApiArchivesTenantRaBranchesNameResponse, error)

	// GetApiArchivesTenantRaBranchesNameVerificationWithResponse request
	GetApiArchivesTenantRaBranchesNameVerificationWithResponse(ctx context.Context, tenant string, ra string, name string, reqEditors ...RequestEditorFn) (*GetApiArchivesTenantRaBranchesNameVerificationResponse, error)

	// GetApiArchivesTenantRaClaimsIdWithResponse request
	GetApiArchivesTenantRaClaimsIdWithResponse(ctx context.Context, tenant string, ra string, id string, reqEditors ...RequestEditorFn) (*GetApiArchivesTenantRaClaimsIdResponse, error)

	// PostApiArchivesTenantRaGqlWithResponse request
	PostApiArchivesTenantRaGqlWithResponse(ctx context.Context, tenant string, ra string, reqEditors ...RequestEditorFn) (*PostApiArchivesTenantRaGqlResponse, error)

	// GetApiTenantsTenantUsersWithResponse request
	GetApiTenantsTenantUsersWithResponse(ctx context.Context, tenant string, reqEditors ...RequestEditorFn) (*GetApiTenantsTenantUsersResponse, error)

	// PostApiTenantsTenantUsersWithBodyWithResponse request with any body
	PostApiTenantsTenantUsersWithBodyWithResponse(ctx context.Context, tenant string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiTenantsTenantUsersResponse, error)

	PostApiTenantsTenantUsersWithResponse(ctx context.Context, tenant string, body PostApiTenantsTenantUsersJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiTenantsTenantUsersResponse, error)

	// DeleteApiTenantsTenantUsersSubjectGrantsWithResponse request
	DeleteApiTenantsTenantUsersSubjectGrantsWithResponse(ctx context.Context, tenant string, subject string, reqEditors ...RequestEditorFn) (*DeleteApiTenantsTenantUsersSubjectGrantsResponse, error)

	// PostApiTenantsTenantUsersSubjectGrantsWithBodyWithResponse request with any body
	PostApiTenantsTenantUsersSubjectGrantsWithBodyWithResponse(ctx context.Context, tenant string, subject string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiTenantsTenantUsersSubjectGrantsResponse, error)

	PostApiTenantsTenantUsersSubjectGrantsWithResponse(ctx context.Context, tenant string, subject string, body PostApiTenantsTenantUsersSubjectGrantsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiTenantsTenantUsersSubjectGrantsResponse, error)

	// GetApiUsersWithResponse request
	GetApiUsersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiUsersResponse, error)

	// PatchApiUsersSubjectWithBodyWithResponse request with any body
	PatchApiUsersSubjectWithBodyWithResponse(ctx context.Context, subject string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchApiUsersSubjectResponse, error)

	PatchApiUsersSubjectWithResponse(ctx context.Context, subject string, body PatchApiUsersSubjectJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchApiUsersSubjectResponse, error)
}

type GetApiArchivesTenantRaResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetArchiveResp
}

// Status returns HTTPResponse.Status
func (r GetApiArchivesTenantRaResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiArchivesTenantRaResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiArchivesTenantRaResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PatchApiArchivesTenantRaResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetArchiveResp
}

// Status returns HTTPResponse.Status
func (r PatchApiArchivesTenantRaResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchApiArchivesTenantRaResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PatchApiArchivesTenantRaResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiArchivesTenantRaBranchesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListBranchesResp
}

// Status returns HTTPResponse.Status
func (r GetApiArchivesTenantRaBranchesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiArchivesTenantRaBranchesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiArchivesTenantRaBranchesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiArchivesTenantRaBranchesNameResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *BranchResp
}

// Status returns HTTPResponse.Status
func (r GetApiArchivesTenantRaBranchesNameResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiArchivesTenantRaBranchesNameResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiArchivesTenantRaBranchesNameResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiArchivesTenantRaBranchesNameVerificationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *VerificationResp
}

// Status returns HTTPResponse.Status
func (r GetApiArchivesTenantRaBranchesNameVerificationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiArchivesTenantRaBranchesNameVerificationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiArchivesTenantRaBranchesNameVerificationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiArchivesTenantRaClaimsIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ClaimView
}

// Status returns HTTPResponse.Status
func (r GetApiArchivesTenantRaClaimsIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiArchivesTenantRaClaimsIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiArchivesTenantRaClaimsIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostApiArchivesTenantRaGqlResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostApiArchivesTenantRaGqlResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiArchivesTenantRaGqlResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostApiArchivesTenantRaGqlResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiTenantsTenantUsersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListTenantUsersResp
}

// Status returns HTTPResponse.Status
func (r GetApiTenantsTenantUsersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiTenantsTenantUsersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiTenantsTenantUsersResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostApiTenantsTenantUsersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AdmitUserResp
}

// Status returns HTTPResponse.Status
func (r PostApiTenantsTenantUsersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiTenantsTenantUsersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostApiTenantsTenantUsersResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteApiTenantsTenantUsersSubjectGrantsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GrantRoleResp
}

// Status returns HTTPResponse.Status
func (r DeleteApiTenantsTenantUsersSubjectGrantsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteApiTenantsTenantUsersSubjectGrantsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteApiTenantsTenantUsersSubjectGrantsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostApiTenantsTenantUsersSubjectGrantsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GrantRoleResp
}

// Status returns HTTPResponse.Status
func (r PostApiTenantsTenantUsersSubjectGrantsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiTenantsTenantUsersSubjectGrantsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostApiTenantsTenantUsersSubjectGrantsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetApiUsersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListSubjectsResp
}

// Status returns HTTPResponse.Status
func (r GetApiUsersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiUsersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetApiUsersResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PatchApiUsersSubjectResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SubjectView
}

// Status returns HTTPResponse.Status
func (r PatchApiUsersSubjectResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchApiUsersSubjectResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PatchApiUsersSubjectResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetApiArchivesTenantRaWithResponse request returning *GetApiArchivesTenantRaResponse
func (c *ClientWithResponses) GetApiArchivesTenantRaWithResponse(ctx context.Context, tenant string, ra string, reqEditors ...RequestEditorFn) (*GetApiArchivesTenantRaResponse, error) {
	rsp, err := c.GetApiArchivesTenantRa(ctx, tenant, ra, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiArchivesTenantRaResponse(rsp)
}

// PatchApiArchivesTenantRaWithBodyWithResponse request with arbitrary body returning *PatchApiArchivesTenantRaResponse
func (c *ClientWithResponses) PatchApiArchivesTenantRaWithBodyWithResponse(ctx context.Context, tenant string, ra string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchApiArchivesTenantRaResponse, error) {
	rsp, err := c.PatchApiArchivesTenantRaWithBody(ctx, tenant, ra, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchApiArchivesTenantRaResponse(rsp)
}

func (c *ClientWithResponses) PatchApiArchivesTenantRaWithResponse(ctx context.Context, tenant string, ra string, body PatchApiArchivesTenantRaJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchApiArchivesTenantRaResponse, error) {
	rsp, err := c.PatchApiArchivesTenantRa(ctx, tenant, ra, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchApiArchivesTenantRaResponse(rsp)
}

// GetApiArchivesTenantRaBranchesWithResponse request returning *GetApiArchivesTenantRaBranchesResponse
func (c *ClientWithResponses) GetApiArchivesTenantRaBranchesWithResponse(ctx context.Context, tenant string, ra string, reqEditors ...RequestEditorFn) (*GetApiArchivesTenantRaBranchesResponse, error) {
	rsp, err := c.GetApiArchivesTenantRaBranches(ctx, tenant, ra, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiArchivesTenantRaBranchesResponse(rsp)
}

// GetApiArchivesTenantRaBranchesNameWithResponse request returning *GetApiArchivesTenantRaBranchesNameResponse
func (c *ClientWithResponses) GetApiArchivesTenantRaBranchesNameWithResponse(ctx context.Context, tenant string, ra string, name string, reqEditors ...RequestEditorFn) (*GetApiArchivesTenantRaBranchesNameResponse, error) {
	rsp, err := c.GetApiArchivesTenantRaBranchesName(ctx, tenant, ra, name, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiArchivesTenantRaBranchesNameResponse(rsp)
}

// GetApiArchivesTenantRaBranchesNameVerificationWithResponse request returning *GetApiArchivesTenantRaBranchesNameVerificationResponse
func (c *ClientWithResponses) GetApiArchivesTenantRaBranchesNameVerificationWithResponse(ctx context.Context, tenant string, ra string, name string, reqEditors ...RequestEditorFn) (*GetApiArchivesTenantRaBranchesNameVerificationResponse, error) {
	rsp, err := c.GetApiArchivesTenantRaBranchesNameVerification(ctx, tenant, ra, name, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiArchivesTenantRaBranchesNameVerificationResponse(rsp)
}

// GetApiArchivesTenantRaClaimsIdWithResponse request returning *GetApiArchivesTenantRaClaimsIdResponse
func (c *ClientWithResponses) GetApiArchivesTenantRaClaimsIdWithResponse(ctx context.Context, tenant string, ra string, id string, reqEditors ...RequestEditorFn) (*GetApiArchivesTenantRaClaimsIdResponse, error) {
	rsp, err := c.GetApiArchivesTenantRaClaimsId(ctx, tenant, ra, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiArchivesTenantRaClaimsIdResponse(rsp)
}

// PostApiArchivesTenantRaGqlWithResponse request returning *PostApiArchivesTenantRaGqlResponse
func (c *ClientWithResponses) PostApiArchivesTenantRaGqlWithResponse(ctx context.Context, tenant string, ra string, reqEditors ...RequestEditorFn) (*PostApiArchivesTenantRaGqlResponse, error) {
	rsp, err := c.PostApiArchivesTenantRaGql(ctx, tenant, ra, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiArchivesTenantRaGqlResponse(rsp)
}

// GetApiTenantsTenantUsersWithResponse request returning *GetApiTenantsTenantUsersResponse
func (c *ClientWithResponses) GetApiTenantsTenantUsersWithResponse(ctx context.Context, tenant string, reqEditors ...RequestEditorFn) (*GetApiTenantsTenantUsersResponse, error) {
	rsp, err := c.GetApiTenantsTenantUsers(ctx, tenant, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiTenantsTenantUsersResponse(rsp)
}

// PostApiTenantsTenantUsersWithBodyWithResponse request with arbitrary body returning *PostApiTenantsTenantUsersResponse
func (c *ClientWithResponses) PostApiTenantsTenantUsersWithBodyWithResponse(ctx context.Context, tenant string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiTenantsTenantUsersResponse, error) {
	rsp, err := c.PostApiTenantsTenantUsersWithBody(ctx, tenant, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiTenantsTenantUsersResponse(rsp)
}

func (c *ClientWithResponses) PostApiTenantsTenantUsersWithResponse(ctx context.Context, tenant string, body PostApiTenantsTenantUsersJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiTenantsTenantUsersResponse, error) {
	rsp, err := c.PostApiTenantsTenantUsers(ctx, tenant, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiTenantsTenantUsersResponse(rsp)
}

// DeleteApiTenantsTenantUsersSubjectGrantsWithResponse request returning *DeleteApiTenantsTenantUsersSubjectGrantsResponse
func (c *ClientWithResponses) DeleteApiTenantsTenantUsersSubjectGrantsWithResponse(ctx context.Context, tenant string, subject string, reqEditors ...RequestEditorFn) (*DeleteApiTenantsTenantUsersSubjectGrantsResponse, error) {
	rsp, err := c.DeleteApiTenantsTenantUsersSubjectGrants(ctx, tenant, subject, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteApiTenantsTenantUsersSubjectGrantsResponse(rsp)
}

// PostApiTenantsTenantUsersSubjectGrantsWithBodyWithResponse request with arbitrary body returning *PostApiTenantsTenantUsersSubjectGrantsResponse
func (c *ClientWithResponses) PostApiTenantsTenantUsersSubjectGrantsWithBodyWithResponse(ctx context.Context, tenant string, subject string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiTenantsTenantUsersSubjectGrantsResponse, error) {
	rsp, err := c.PostApiTenantsTenantUsersSubjectGrantsWithBody(ctx, tenant, subject, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiTenantsTenantUsersSubjectGrantsResponse(rsp)
}

func (c *ClientWithResponses) PostApiTenantsTenantUsersSubjectGrantsWithResponse(ctx context.Context, tenant string, subject string, body PostApiTenantsTenantUsersSubjectGrantsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiTenantsTenantUsersSubjectGrantsResponse, error) {
	rsp, err := c.PostApiTenantsTenantUsersSubjectGrants(ctx, tenant, subject, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiTenantsTenantUsersSubjectGrantsResponse(rsp)
}

// GetApiUsersWithResponse request returning *GetApiUsersResponse
func (c *ClientWithResponses) GetApiUsersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiUsersResponse, error) {
	rsp, err := c.GetApiUsers(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiUsersResponse(rsp)
}

// PatchApiUsersSubjectWithBodyWithResponse request with arbitrary body returning *PatchApiUsersSubjectResponse
func (c *ClientWithResponses) PatchApiUsersSubjectWithBodyWithResponse(ctx context.Context, subject string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchApiUsersSubjectResponse, error) {
	rsp, err := c.PatchApiUsersSubjectWithBody(ctx, subject, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchApiUsersSubjectResponse(rsp)
}

func (c *ClientWithResponses) PatchApiUsersSubjectWithResponse(ctx context.Context, subject string, body PatchApiUsersSubjectJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchApiUsersSubjectResponse, error) {
	rsp, err := c.PatchApiUsersSubject(ctx, subject, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchApiUsersSubjectResponse(rsp)
}

// ParseGetApiArchivesTenantRaResponse parses an HTTP response from a GetApiArchivesTenantRaWithResponse call
func ParseGetApiArchivesTenantRaResponse(rsp *http.Response) (*GetApiArchivesTenantRaResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiArchivesTenantRaResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetArchiveResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePatchApiArchivesTenantRaResponse parses an HTTP response from a PatchApiArchivesTenantRaWithResponse call
func ParsePatchApiArchivesTenantRaResponse(rsp *http.Response) (*PatchApiArchivesTenantRaResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchApiArchivesTenantRaResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetArchiveResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiArchivesTenantRaBranchesResponse parses an HTTP response from a GetApiArchivesTenantRaBranchesWithResponse call
func ParseGetApiArchivesTenantRaBranchesResponse(rsp *http.Response) (*GetApiArchivesTenantRaBranchesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiArchivesTenantRaBranchesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListBranchesResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiArchivesTenantRaBranchesNameResponse parses an HTTP response from a GetApiArchivesTenantRaBranchesNameWithResponse call
func ParseGetApiArchivesTenantRaBranchesNameResponse(rsp *http.Response) (*GetApiArchivesTenantRaBranchesNameResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiArchivesTenantRaBranchesNameResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BranchResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiArchivesTenantRaBranchesNameVerificationResponse parses an HTTP response from a GetApiArchivesTenantRaBranchesNameVerificationWithResponse call
func ParseGetApiArchivesTenantRaBranchesNameVerificationResponse(rsp *http.Response) (*GetApiArchivesTenantRaBranchesNameVerificationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiArchivesTenantRaBranchesNameVerificationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest VerificationResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiArchivesTenantRaClaimsIdResponse parses an HTTP response from a GetApiArchivesTenantRaClaimsIdWithResponse call
func ParseGetApiArchivesTenantRaClaimsIdResponse(rsp *http.Response) (*GetApiArchivesTenantRaClaimsIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiArchivesTenantRaClaimsIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ClaimView
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostApiArchivesTenantRaGqlResponse parses an HTTP response from a PostApiArchivesTenantRaGqlWithResponse call
func ParsePostApiArchivesTenantRaGqlResponse(rsp *http.Response) (*PostApiArchivesTenantRaGqlResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiArchivesTenantRaGqlResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetApiTenantsTenantUsersResponse parses an HTTP response from a GetApiTenantsTenantUsersWithResponse call
func ParseGetApiTenantsTenantUsersResponse(rsp *http.Response) (*GetApiTenantsTenantUsersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiTenantsTenantUsersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListTenantUsersResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostApiTenantsTenantUsersResponse parses an HTTP response from a PostApiTenantsTenantUsersWithResponse call
func ParsePostApiTenantsTenantUsersResponse(rsp *http.Response) (*PostApiTenantsTenantUsersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiTenantsTenantUsersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AdmitUserResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeleteApiTenantsTenantUsersSubjectGrantsResponse parses an HTTP response from a DeleteApiTenantsTenantUsersSubjectGrantsWithResponse call
func ParseDeleteApiTenantsTenantUsersSubjectGrantsResponse(rsp *http.Response) (*DeleteApiTenantsTenantUsersSubjectGrantsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteApiTenantsTenantUsersSubjectGrantsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GrantRoleResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostApiTenantsTenantUsersSubjectGrantsResponse parses an HTTP response from a PostApiTenantsTenantUsersSubjectGrantsWithResponse call
func ParsePostApiTenantsTenantUsersSubjectGrantsResponse(rsp *http.Response) (*PostApiTenantsTenantUsersSubjectGrantsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiTenantsTenantUsersSubjectGrantsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GrantRoleResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiUsersResponse parses an HTTP response from a GetApiUsersWithResponse call
func ParseGetApiUsersResponse(rsp *http.Response) (*GetApiUsersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiUsersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListSubjectsResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePatchApiUsersSubjectResponse parses an HTTP response from a PatchApiUsersSubjectWithResponse call
func ParsePatchApiUsersSubjectResponse(rsp *http.Response) (*PatchApiUsersSubjectResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchApiUsersSubjectResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SubjectView
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
