// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Edge struct {
	ID           string          `json:"id"`
	SourceNodeID string          `json:"source_node_id"`
	TargetNodeID string          `json:"target_node_id"`
	Type         string          `json:"type"`
	Confidence   sql.NullFloat64 `json:"confidence"`
	RunID        sql.NullString  `json:"run_id"`
	CreatedAt    time.Time       `json:"created_at"`
}

type Node struct {
	ID                    string          `json:"id"`
	Level                 int16           `json:"level"`
	ContentClass          string          `json:"content_class"`
	ContentType           string          `json:"content_type"`
	EncodingClass         string          `json:"encoding_class"`
	EncodingFormat        string          `json:"encoding_format"`
	ContentSha256         string          `json:"content_sha256"`
	ContentLen            int64           `json:"content_len"`
	ContentCached         sql.NullString  `json:"content_cached"`
	CreatedAt             time.Time       `json:"created_at"`
	ArtifactCreatedAt     sql.NullTime    `json:"artifact_created_at"`
	ArtifactCreatedAtBlur sql.NullString  `json:"artifact_created_at_blur"`
	Origin                sql.NullString  `json:"origin"`
	OriginalName          sql.NullString  `json:"original_name"`
	ValidFrom             sql.NullTime    `json:"valid_from"`
	ValidFromBlur         sql.NullString  `json:"valid_from_blur"`
	ValidUntil            sql.NullTime    `json:"valid_until"`
	ValidUntilBlur        sql.NullString  `json:"valid_until_blur"`
	Confidence            sql.NullFloat64 `json:"confidence"`
}

type Run struct {
	ID             string    `json:"id"`
	WorkerConfigID string    `json:"worker_config_id"`
	CreatedAt      time.Time `json:"created_at"`
}
