// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nodes.sql

package db

import (
	"context"
	"database/sql"
)

const getNode = `-- name: GetNode :one
SELECT id, level, content_class, content_type, encoding_class, encoding_format, content_sha256, content_len, content_cached, created_at, artifact_created_at, artifact_created_at_blur, origin, original_name, valid_from, valid_from_blur, valid_until, valid_until_blur, confidence, title FROM nodes WHERE id = $1
`

func (q *Queries) GetNode(ctx context.Context, id string) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Level,
		&i.ContentClass,
		&i.ContentType,
		&i.EncodingClass,
		&i.EncodingFormat,
		&i.ContentSha256,
		&i.ContentLen,
		&i.ContentCached,
		&i.CreatedAt,
		&i.ArtifactCreatedAt,
		&i.ArtifactCreatedAtBlur,
		&i.Origin,
		&i.OriginalName,
		&i.ValidFrom,
		&i.ValidFromBlur,
		&i.ValidUntil,
		&i.ValidUntilBlur,
		&i.Confidence,
		&i.Title,
	)
	return i, err
}

const insertNode = `-- name: InsertNode :exec
INSERT INTO nodes (
    id, level, content_class, content_type, encoding_class, encoding_format,
    content_sha256, content_len, content_cached, title,
    artifact_created_at, artifact_created_at_blur, origin, original_name,
    valid_from, valid_from_blur, valid_until, valid_until_blur, confidence
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13, $14,
    $15, $16, $17, $18, $19
)
`

type InsertNodeParams struct {
	ID                    string          `json:"id"`
	Level                 int16           `json:"level"`
	ContentClass          string          `json:"content_class"`
	ContentType           string          `json:"content_type"`
	EncodingClass         string          `json:"encoding_class"`
	EncodingFormat        string          `json:"encoding_format"`
	ContentSha256         string          `json:"content_sha256"`
	ContentLen            int64           `json:"content_len"`
	ContentCached         sql.NullString  `json:"content_cached"`
	Title                 sql.NullString  `json:"title"`
	ArtifactCreatedAt     sql.NullTime    `json:"artifact_created_at"`
	ArtifactCreatedAtBlur sql.NullString  `json:"artifact_created_at_blur"`
	Origin                sql.NullString  `json:"origin"`
	OriginalName          sql.NullString  `json:"original_name"`
	ValidFrom             sql.NullTime    `json:"valid_from"`
	ValidFromBlur         sql.NullString  `json:"valid_from_blur"`
	ValidUntil            sql.NullTime    `json:"valid_until"`
	ValidUntilBlur        sql.NullString  `json:"valid_until_blur"`
	Confidence            sql.NullFloat64 `json:"confidence"`
}

func (q *Queries) InsertNode(ctx context.Context, arg InsertNodeParams) error {
	_, err := q.db.ExecContext(ctx, insertNode,
		arg.ID,
		arg.Level,
		arg.ContentClass,
		arg.ContentType,
		arg.EncodingClass,
		arg.EncodingFormat,
		arg.ContentSha256,
		arg.ContentLen,
		arg.ContentCached,
		arg.Title,
		arg.ArtifactCreatedAt,
		arg.ArtifactCreatedAtBlur,
		arg.Origin,
		arg.OriginalName,
		arg.ValidFrom,
		arg.ValidFromBlur,
		arg.ValidUntil,
		arg.ValidUntilBlur,
		arg.Confidence,
	)
	return err
}

const listNodes = `-- name: ListNodes :many
SELECT id, level, content_class, content_type, encoding_class, encoding_format, content_sha256, content_len, content_cached, created_at, artifact_created_at, artifact_created_at_blur, origin, original_name, valid_from, valid_from_blur, valid_until, valid_until_blur, confidence, title FROM nodes ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListNodesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListNodes(ctx context.Context, arg ListNodesParams) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listNodes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.ContentClass,
			&i.ContentType,
			&i.EncodingClass,
			&i.EncodingFormat,
			&i.ContentSha256,
			&i.ContentLen,
			&i.ContentCached,
			&i.CreatedAt,
			&i.ArtifactCreatedAt,
			&i.ArtifactCreatedAtBlur,
			&i.Origin,
			&i.OriginalName,
			&i.ValidFrom,
			&i.ValidFromBlur,
			&i.ValidUntil,
			&i.ValidUntilBlur,
			&i.Confidence,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByContentClass = `-- name: ListNodesByContentClass :many
SELECT id, level, content_class, content_type, encoding_class, encoding_format, content_sha256, content_len, content_cached, created_at, artifact_created_at, artifact_created_at_blur, origin, original_name, valid_from, valid_from_blur, valid_until, valid_until_blur, confidence, title FROM nodes WHERE content_class = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListNodesByContentClassParams struct {
	ContentClass string `json:"content_class"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
}

func (q *Queries) ListNodesByContentClass(ctx context.Context, arg ListNodesByContentClassParams) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listNodesByContentClass, arg.ContentClass, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.ContentClass,
			&i.ContentType,
			&i.EncodingClass,
			&i.EncodingFormat,
			&i.ContentSha256,
			&i.ContentLen,
			&i.ContentCached,
			&i.CreatedAt,
			&i.ArtifactCreatedAt,
			&i.ArtifactCreatedAtBlur,
			&i.Origin,
			&i.OriginalName,
			&i.ValidFrom,
			&i.ValidFromBlur,
			&i.ValidUntil,
			&i.ValidUntilBlur,
			&i.Confidence,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByContentClassAndType = `-- name: ListNodesByContentClassAndType :many
SELECT id, level, content_class, content_type, encoding_class, encoding_format, content_sha256, content_len, content_cached, created_at, artifact_created_at, artifact_created_at_blur, origin, original_name, valid_from, valid_from_blur, valid_until, valid_until_blur, confidence, title FROM nodes WHERE content_class = $1 AND content_type = $2 ORDER BY created_at DESC LIMIT $3 OFFSET $4
`

type ListNodesByContentClassAndTypeParams struct {
	ContentClass string `json:"content_class"`
	ContentType  string `json:"content_type"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
}

func (q *Queries) ListNodesByContentClassAndType(ctx context.Context, arg ListNodesByContentClassAndTypeParams) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listNodesByContentClassAndType,
		arg.ContentClass,
		arg.ContentType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.ContentClass,
			&i.ContentType,
			&i.EncodingClass,
			&i.EncodingFormat,
			&i.ContentSha256,
			&i.ContentLen,
			&i.ContentCached,
			&i.CreatedAt,
			&i.ArtifactCreatedAt,
			&i.ArtifactCreatedAtBlur,
			&i.Origin,
			&i.OriginalName,
			&i.ValidFrom,
			&i.ValidFromBlur,
			&i.ValidUntil,
			&i.ValidUntilBlur,
			&i.Confidence,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByLevel = `-- name: ListNodesByLevel :many
SELECT id, level, content_class, content_type, encoding_class, encoding_format, content_sha256, content_len, content_cached, created_at, artifact_created_at, artifact_created_at_blur, origin, original_name, valid_from, valid_from_blur, valid_until, valid_until_blur, confidence, title FROM nodes WHERE level = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListNodesByLevelParams struct {
	Level  int16 `json:"level"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListNodesByLevel(ctx context.Context, arg ListNodesByLevelParams) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listNodesByLevel, arg.Level, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.ContentClass,
			&i.ContentType,
			&i.EncodingClass,
			&i.EncodingFormat,
			&i.ContentSha256,
			&i.ContentLen,
			&i.ContentCached,
			&i.CreatedAt,
			&i.ArtifactCreatedAt,
			&i.ArtifactCreatedAtBlur,
			&i.Origin,
			&i.OriginalName,
			&i.ValidFrom,
			&i.ValidFromBlur,
			&i.ValidUntil,
			&i.ValidUntilBlur,
			&i.Confidence,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nodeExistsBySha256 = `-- name: NodeExistsBySha256 :one
SELECT id FROM nodes WHERE level = 0 AND content_sha256 = $1 LIMIT 1
`

func (q *Queries) NodeExistsBySha256(ctx context.Context, contentSha256 string) (string, error) {
	row := q.db.QueryRowContext(ctx, nodeExistsBySha256, contentSha256)
	var id string
	err := row.Scan(&id)
	return id, err
}

const searchNodesByContent = `-- name: SearchNodesByContent :many
SELECT id, level, content_class, content_type, encoding_class, encoding_format, content_sha256, content_len, content_cached, created_at, artifact_created_at, artifact_created_at_blur, origin, original_name, valid_from, valid_from_blur, valid_until, valid_until_blur, confidence, title FROM nodes WHERE content_cached IS NOT NULL AND content_tsv @@ plainto_tsquery('english', $1) ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type SearchNodesByContentParams struct {
	PlaintoTsquery string `json:"plainto_tsquery"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) SearchNodesByContent(ctx context.Context, arg SearchNodesByContentParams) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, searchNodesByContent, arg.PlaintoTsquery, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.ContentClass,
			&i.ContentType,
			&i.EncodingClass,
			&i.EncodingFormat,
			&i.ContentSha256,
			&i.ContentLen,
			&i.ContentCached,
			&i.CreatedAt,
			&i.ArtifactCreatedAt,
			&i.ArtifactCreatedAtBlur,
			&i.Origin,
			&i.OriginalName,
			&i.ValidFrom,
			&i.ValidFromBlur,
			&i.ValidUntil,
			&i.ValidUntilBlur,
			&i.Confidence,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
