/**
 * package: scripts / build
 * type:    tool
 * job:     fold a vite build into one self-contained dist/explorer.html
 * limits:  packaging only; the bundling itself is vite's (-> vite.config.ts)
 *
 * Lets the spike open without a server: bare specifiers need a bundle anyway, so this
 * inlines it and makes the script classic, which `file://` runs. The FA2-worker layout
 * cannot work there — a Blob-URL worker needs a real origin.
 */

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const dist = new URL('../dist/', import.meta.url).pathname;
const assets = join(dist, 'assets');

const files = readdirSync(assets);
const js = files.find((f) => f.endsWith('.js'));
const css = files.find((f) => f.endsWith('.css'));
if (!js) throw new Error('no bundled js in dist/assets — run `vite build` first');

let html = readFileSync(join(dist, 'index.html'), 'utf8');
const script = readFileSync(join(assets, js), 'utf8');
const style = css ? readFileSync(join(assets, css), 'utf8') : '';

html = html
  .replace(/<script[^>]*src="[^"]*"[^>]*><\/script>/, '')
  .replace(/<link[^>]*rel="stylesheet"[^>]*>/, '')
  .replace('</head>', `<style>\n${style}\n</style>\n</head>`)
  .replace('</body>', `<script>\n${script}\n</script>\n</body>`);

// Written to the spike root, not dist/, and committed — like the repo's other
// generated artifacts. It is the zero-setup way to look at the spike: no npm,
// no server, just open the file.
const out = new URL('../explorer.html', import.meta.url).pathname;
writeFileSync(out, `<!-- GENERATED by npm run build:single — do not edit -->\n${html}`);
// dist/ is left in place: `make` produces both artifacts, the static bundle to
// serve and the single file to hand to somebody.

const kb = (Buffer.byteLength(html) / 1024).toFixed(0);
process.stdout.write(`>> ${out}  (${kb} KB, self-contained — open it directly)\n`);
