/**
 * Folds a vite build into one self-contained file: dist/explorer.html.
 *
 * Exists so the spike can be opened without running a server. The page's imports
 * are bare specifiers ('sigma', 'graphology'), which no browser can resolve from
 * disk, so a bundle is required either way — this just inlines it into the HTML
 * and rewrites the module script as a classic one, which `file://` will run.
 *
 * The ForceAtlas2-worker layout will not work from file://: it builds its worker
 * from a Blob URL, and a file:// page has an opaque origin. Every other layout does.
 */

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const dist = new URL('../dist/', import.meta.url).pathname;
const assets = join(dist, 'assets');

const files = readdirSync(assets);
const js = files.find((f) => f.endsWith('.js'));
const css = files.find((f) => f.endsWith('.css'));
if (!js) throw new Error('no bundled js in dist/assets — run `vite build` first');

let html = readFileSync(join(dist, 'index.html'), 'utf8');
const script = readFileSync(join(assets, js), 'utf8');
const style = css ? readFileSync(join(assets, css), 'utf8') : '';

html = html
  .replace(/<script[^>]*src="[^"]*"[^>]*><\/script>/, '')
  .replace(/<link[^>]*rel="stylesheet"[^>]*>/, '')
  .replace('</head>', `<style>\n${style}\n</style>\n</head>`)
  .replace('</body>', `<script>\n${script}\n</script>\n</body>`);

// Written to the spike root, not dist/, and committed — like the repo's other
// generated artifacts. It is the zero-setup way to look at the spike: no npm,
// no server, just open the file.
const out = new URL('../explorer.html', import.meta.url).pathname;
writeFileSync(out, `<!-- GENERATED by npm run build:single — do not edit -->\n${html}`);
// dist/ is left in place: `make` produces both artifacts, the static bundle to
// serve and the single file to hand to somebody.

const kb = (Buffer.byteLength(html) / 1024).toFixed(0);
process.stdout.write(`>> ${out}  (${kb} KB, self-contained — open it directly)\n`);
