/**
 * package: scripts / build
 * type:    tool
 * job:     fold a vite build into one self-contained explorer.html
 * limits:  packaging only; the bundling itself is vite's (-> vite.config.ts)
 *
 * A module bundle needs a real origin; a classic script doesn't, so this inlines
 * .build/'s output into one file a browser can run from anywhere — opened directly, or
 * embedded and served by ranke-db itself (-> ../../adapters/endpoints/rest_http). The
 * FA2-worker layout can't run from a Blob URL without a real origin either way, so it
 * stays out of scope for a `file://`-opened copy.
 */

import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const build = new URL('../.build/', import.meta.url).pathname;
const assets = join(build, 'assets');

const files = readdirSync(assets);
const js = files.find((f) => f.endsWith('.js'));
const css = files.find((f) => f.endsWith('.css'));
const svg = files.find((f) => f.endsWith('.svg'));
if (!js) throw new Error('no bundled js in .build/assets — run `vite build` first');

let html = readFileSync(join(build, 'index.html'), 'utf8');
const script = readFileSync(join(assets, js), 'utf8');
const style = css ? readFileSync(join(assets, css), 'utf8') : '';

html = html
  .replace(/<script[^>]*src="[^"]*"[^>]*><\/script>/, '')
  .replace(/<link[^>]*rel="stylesheet"[^>]*>/, '')
  .replace('</head>', `<style>\n${style}\n</style>\n</head>`)
  .replace('</body>', `<script>\n${script}\n</script>\n</body>`);

// The icon is linked by URL, and `assetsInlineLimit` does not reach an asset referenced from
// the HTML, so it arrives here as a file like the script and the style.
if (svg) {
  const uri = `data:image/svg+xml,${encodeURIComponent(readFileSync(join(assets, svg), 'utf8'))}`;
  html = html.replace(/(<link[^>]*rel="icon"[^>]*href=")[^"]*(")/, (_, open, close) => open + uri + close);
}

// Self-contained is the whole point, and a leftover URL only shows as a missing file once the
// page is opened from somewhere else.
const dangling = html.match(/(?:src|href)="[^"]*\/assets\/[^"]*"/);
if (dangling) throw new Error(`${dangling[0]} was left pointing at a file beside explorer.html`);

// Written to dist/, never .build/: a built artifact never shares a directory with
// source, and dist/ is committed — like the repo's other generated artifacts — while
// .build/ is scratch, gitignored, rebuilt by every `make build`. Opened directly, or
// embedded and served by ranke-db itself (-> ../../adapters/endpoints/rest_http).
const outDir = new URL('../dist/', import.meta.url).pathname;
mkdirSync(outDir, { recursive: true });
const out = join(outDir, 'explorer.html');
writeFileSync(out, `<!-- GENERATED by npm run build:single — do not edit -->\n${html}`);

const kb = (Buffer.byteLength(html) / 1024).toFixed(0);
process.stdout.write(`>> ${out}  (${kb} KB, self-contained — open it directly)\n`);
