// Package apiclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package apiclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// CreateRunReq defines model for CreateRunReq.
type CreateRunReq struct {
	WorkerConfigId string `json:"worker_config_id"`
}

// CreateRunResp defines model for CreateRunResp.
type CreateRunResp struct {
	RunId string `json:"run_id"`
}

// EdgeProvenanceResp defines model for EdgeProvenanceResp.
type EdgeProvenanceResp struct {
	Edge             EdgeResponse `json:"edge"`
	RunId            string       `json:"run_id"`
	WorkerConfigNode NodeResponse `json:"worker_config_node"`
}

// EdgeResponse defines model for EdgeResponse.
type EdgeResponse struct {
	Confidence   float32 `json:"confidence"`
	CreatedAt    string  `json:"created_at"`
	Id           string  `json:"id"`
	RunId        string  `json:"run_id"`
	SourceNodeId string  `json:"source_node_id"`
	TargetNodeId string  `json:"target_node_id"`
	Type         string  `json:"type"`
}

// GetEntityResp defines model for GetEntityResp.
type GetEntityResp struct {
	Entity    NodeResponse       `json:"entity"`
	Relations []RelationResponse `json:"relations"`
}

// GetEntityTimelineResp defines model for GetEntityTimelineResp.
type GetEntityTimelineResp struct {
	Relations []RelationResponse `json:"relations"`
}

// GetNodeEdgesResp defines model for GetNodeEdgesResp.
type GetNodeEdgesResp struct {
	Edges []EdgeResponse `json:"edges"`
}

// GetQueueResp defines model for GetQueueResp.
type GetQueueResp struct {
	Nodes []NodeResponse `json:"nodes"`
}

// ListEdgesResp defines model for ListEdgesResp.
type ListEdgesResp struct {
	Edges []EdgeResponse `json:"edges"`
}

// ListNodesResp defines model for ListNodesResp.
type ListNodesResp struct {
	Nodes []NodeResponse `json:"nodes"`
}

// ListRelationsResp defines model for ListRelationsResp.
type ListRelationsResp struct {
	Relations []RelationResponse `json:"relations"`
}

// NodeResponse defines model for NodeResponse.
type NodeResponse struct {
	ArtifactCreatedAt     string  `json:"artifact_created_at"`
	ArtifactCreatedAtBlur string  `json:"artifact_created_at_blur"`
	Confidence            float32 `json:"confidence"`
	Content               string  `json:"content"`
	ContentClass          string  `json:"content_class"`
	ContentLen            int     `json:"content_len"`
	ContentSha256         string  `json:"content_sha256"`
	ContentType           string  `json:"content_type"`
	CreatedAt             string  `json:"created_at"`
	EncodingClass         string  `json:"encoding_class"`
	EncodingFormat        string  `json:"encoding_format"`
	Id                    string  `json:"id"`
	Level                 int     `json:"level"`
	Origin                string  `json:"origin"`
	OriginalName          string  `json:"original_name"`
	ValidFrom             string  `json:"valid_from"`
	ValidFromBlur         string  `json:"valid_from_blur"`
	ValidUntil            string  `json:"valid_until"`
	ValidUntilBlur        string  `json:"valid_until_blur"`
}

// ProvenanceSubgraph defines model for ProvenanceSubgraph.
type ProvenanceSubgraph struct {
	Edges []EdgeResponse `json:"edges"`
	Nodes []NodeResponse `json:"nodes"`
}

// RelationResponse defines model for RelationResponse.
type RelationResponse struct {
	HeadEdges []EdgeResponse `json:"head_edges"`
	Node      NodeResponse   `json:"node"`
	TailEdges []EdgeResponse `json:"tail_edges"`
}

// SearchEntitiesResp defines model for SearchEntitiesResp.
type SearchEntitiesResp struct {
	Entities []NodeResponse `json:"entities"`
}

// PostApiRunsJSONRequestBody defines body for PostApiRuns for application/json ContentType.
type PostApiRunsJSONRequestBody = CreateRunReq

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetApiEdges request
	GetApiEdges(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiEdgesId request
	GetApiEdgesId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiEdgesIdProvenance request
	GetApiEdgesIdProvenance(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiEntities request
	GetApiEntities(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiEntitiesId request
	GetApiEntitiesId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiEntitiesIdTimeline request
	GetApiEntitiesIdTimeline(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiNodes request
	GetApiNodes(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiNodes request
	PostApiNodes(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiNodesId request
	GetApiNodesId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiNodesIdContent request
	GetApiNodesIdContent(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiNodesIdEdges request
	GetApiNodesIdEdges(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiNodesIdProvenance request
	GetApiNodesIdProvenance(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiQueue request
	GetApiQueue(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiRelations request
	GetApiRelations(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiRunsWithBody request with any body
	PostApiRunsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiRuns(ctx context.Context, body PostApiRunsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetApiEdges(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiEdgesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiEdgesId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiEdgesIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiEdgesIdProvenance(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiEdgesIdProvenanceRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiEntities(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiEntitiesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiEntitiesId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiEntitiesIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiEntitiesIdTimeline(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiEntitiesIdTimelineRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiNodes(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiNodesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiNodes(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiNodesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiNodesId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiNodesIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiNodesIdContent(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiNodesIdContentRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiNodesIdEdges(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiNodesIdEdgesRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiNodesIdProvenance(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiNodesIdProvenanceRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiQueue(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiQueueRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiRelations(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiRelationsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiRunsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiRunsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiRuns(ctx context.Context, body PostApiRunsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiRunsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetApiEdgesRequest generates requests for GetApiEdges
func NewGetApiEdgesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/edges")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiEdgesIdRequest generates requests for GetApiEdgesId
func NewGetApiEdgesIdRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/edges/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiEdgesIdProvenanceRequest generates requests for GetApiEdgesIdProvenance
func NewGetApiEdgesIdProvenanceRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/edges/%s/provenance", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiEntitiesRequest generates requests for GetApiEntities
func NewGetApiEntitiesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/entities")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiEntitiesIdRequest generates requests for GetApiEntitiesId
func NewGetApiEntitiesIdRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/entities/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiEntitiesIdTimelineRequest generates requests for GetApiEntitiesIdTimeline
func NewGetApiEntitiesIdTimelineRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/entities/%s/timeline", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiNodesRequest generates requests for GetApiNodes
func NewGetApiNodesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/nodes")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiNodesRequest generates requests for PostApiNodes
func NewPostApiNodesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/nodes")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiNodesIdRequest generates requests for GetApiNodesId
func NewGetApiNodesIdRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/nodes/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiNodesIdContentRequest generates requests for GetApiNodesIdContent
func NewGetApiNodesIdContentRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/nodes/%s/content", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiNodesIdEdgesRequest generates requests for GetApiNodesIdEdges
func NewGetApiNodesIdEdgesRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/nodes/%s/edges", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiNodesIdProvenanceRequest generates requests for GetApiNodesIdProvenance
func NewGetApiNodesIdProvenanceRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/nodes/%s/provenance", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiQueueRequest generates requests for GetApiQueue
func NewGetApiQueueRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/queue")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiRelationsRequest generates requests for GetApiRelations
func NewGetApiRelationsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/relations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiRunsRequest calls the generic PostApiRuns builder with application/json body
func NewPostApiRunsRequest(server string, body PostApiRunsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiRunsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiRunsRequestWithBody generates requests for PostApiRuns with any type of body
func NewPostApiRunsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/runs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetApiEdgesWithResponse request
	GetApiEdgesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiEdgesResponse, error)

	// GetApiEdgesIdWithResponse request
	GetApiEdgesIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetApiEdgesIdResponse, error)

	// GetApiEdgesIdProvenanceWithResponse request
	GetApiEdgesIdProvenanceWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetApiEdgesIdProvenanceResponse, error)

	// GetApiEntitiesWithResponse request
	GetApiEntitiesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiEntitiesResponse, error)

	// GetApiEntitiesIdWithResponse request
	GetApiEntitiesIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetApiEntitiesIdResponse, error)

	// GetApiEntitiesIdTimelineWithResponse request
	GetApiEntitiesIdTimelineWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetApiEntitiesIdTimelineResponse, error)

	// GetApiNodesWithResponse request
	GetApiNodesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiNodesResponse, error)

	// PostApiNodesWithResponse request
	PostApiNodesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostApiNodesResponse, error)

	// GetApiNodesIdWithResponse request
	GetApiNodesIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetApiNodesIdResponse, error)

	// GetApiNodesIdContentWithResponse request
	GetApiNodesIdContentWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetApiNodesIdContentResponse, error)

	// GetApiNodesIdEdgesWithResponse request
	GetApiNodesIdEdgesWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetApiNodesIdEdgesResponse, error)

	// GetApiNodesIdProvenanceWithResponse request
	GetApiNodesIdProvenanceWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetApiNodesIdProvenanceResponse, error)

	// GetApiQueueWithResponse request
	GetApiQueueWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiQueueResponse, error)

	// GetApiRelationsWithResponse request
	GetApiRelationsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiRelationsResponse, error)

	// PostApiRunsWithBodyWithResponse request with any body
	PostApiRunsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiRunsResponse, error)

	PostApiRunsWithResponse(ctx context.Context, body PostApiRunsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiRunsResponse, error)
}

type GetApiEdgesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListEdgesResp
}

// Status returns HTTPResponse.Status
func (r GetApiEdgesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiEdgesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiEdgesIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EdgeResponse
}

// Status returns HTTPResponse.Status
func (r GetApiEdgesIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiEdgesIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiEdgesIdProvenanceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *EdgeProvenanceResp
}

// Status returns HTTPResponse.Status
func (r GetApiEdgesIdProvenanceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiEdgesIdProvenanceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiEntitiesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SearchEntitiesResp
}

// Status returns HTTPResponse.Status
func (r GetApiEntitiesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiEntitiesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiEntitiesIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetEntityResp
}

// Status returns HTTPResponse.Status
func (r GetApiEntitiesIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiEntitiesIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiEntitiesIdTimelineResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetEntityTimelineResp
}

// Status returns HTTPResponse.Status
func (r GetApiEntitiesIdTimelineResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiEntitiesIdTimelineResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiNodesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListNodesResp
}

// Status returns HTTPResponse.Status
func (r GetApiNodesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiNodesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiNodesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostApiNodesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiNodesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiNodesIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NodeResponse
}

// Status returns HTTPResponse.Status
func (r GetApiNodesIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiNodesIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiNodesIdContentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetApiNodesIdContentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiNodesIdContentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiNodesIdEdgesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetNodeEdgesResp
}

// Status returns HTTPResponse.Status
func (r GetApiNodesIdEdgesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiNodesIdEdgesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiNodesIdProvenanceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ProvenanceSubgraph
}

// Status returns HTTPResponse.Status
func (r GetApiNodesIdProvenanceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiNodesIdProvenanceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiQueueResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetQueueResp
}

// Status returns HTTPResponse.Status
func (r GetApiQueueResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiQueueResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiRelationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListRelationsResp
}

// Status returns HTTPResponse.Status
func (r GetApiRelationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiRelationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiRunsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CreateRunResp
}

// Status returns HTTPResponse.Status
func (r PostApiRunsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiRunsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetApiEdgesWithResponse request returning *GetApiEdgesResponse
func (c *ClientWithResponses) GetApiEdgesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiEdgesResponse, error) {
	rsp, err := c.GetApiEdges(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiEdgesResponse(rsp)
}

// GetApiEdgesIdWithResponse request returning *GetApiEdgesIdResponse
func (c *ClientWithResponses) GetApiEdgesIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetApiEdgesIdResponse, error) {
	rsp, err := c.GetApiEdgesId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiEdgesIdResponse(rsp)
}

// GetApiEdgesIdProvenanceWithResponse request returning *GetApiEdgesIdProvenanceResponse
func (c *ClientWithResponses) GetApiEdgesIdProvenanceWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetApiEdgesIdProvenanceResponse, error) {
	rsp, err := c.GetApiEdgesIdProvenance(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiEdgesIdProvenanceResponse(rsp)
}

// GetApiEntitiesWithResponse request returning *GetApiEntitiesResponse
func (c *ClientWithResponses) GetApiEntitiesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiEntitiesResponse, error) {
	rsp, err := c.GetApiEntities(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiEntitiesResponse(rsp)
}

// GetApiEntitiesIdWithResponse request returning *GetApiEntitiesIdResponse
func (c *ClientWithResponses) GetApiEntitiesIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetApiEntitiesIdResponse, error) {
	rsp, err := c.GetApiEntitiesId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiEntitiesIdResponse(rsp)
}

// GetApiEntitiesIdTimelineWithResponse request returning *GetApiEntitiesIdTimelineResponse
func (c *ClientWithResponses) GetApiEntitiesIdTimelineWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetApiEntitiesIdTimelineResponse, error) {
	rsp, err := c.GetApiEntitiesIdTimeline(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiEntitiesIdTimelineResponse(rsp)
}

// GetApiNodesWithResponse request returning *GetApiNodesResponse
func (c *ClientWithResponses) GetApiNodesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiNodesResponse, error) {
	rsp, err := c.GetApiNodes(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiNodesResponse(rsp)
}

// PostApiNodesWithResponse request returning *PostApiNodesResponse
func (c *ClientWithResponses) PostApiNodesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostApiNodesResponse, error) {
	rsp, err := c.PostApiNodes(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiNodesResponse(rsp)
}

// GetApiNodesIdWithResponse request returning *GetApiNodesIdResponse
func (c *ClientWithResponses) GetApiNodesIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetApiNodesIdResponse, error) {
	rsp, err := c.GetApiNodesId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiNodesIdResponse(rsp)
}

// GetApiNodesIdContentWithResponse request returning *GetApiNodesIdContentResponse
func (c *ClientWithResponses) GetApiNodesIdContentWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetApiNodesIdContentResponse, error) {
	rsp, err := c.GetApiNodesIdContent(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiNodesIdContentResponse(rsp)
}

// GetApiNodesIdEdgesWithResponse request returning *GetApiNodesIdEdgesResponse
func (c *ClientWithResponses) GetApiNodesIdEdgesWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetApiNodesIdEdgesResponse, error) {
	rsp, err := c.GetApiNodesIdEdges(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiNodesIdEdgesResponse(rsp)
}

// GetApiNodesIdProvenanceWithResponse request returning *GetApiNodesIdProvenanceResponse
func (c *ClientWithResponses) GetApiNodesIdProvenanceWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetApiNodesIdProvenanceResponse, error) {
	rsp, err := c.GetApiNodesIdProvenance(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiNodesIdProvenanceResponse(rsp)
}

// GetApiQueueWithResponse request returning *GetApiQueueResponse
func (c *ClientWithResponses) GetApiQueueWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiQueueResponse, error) {
	rsp, err := c.GetApiQueue(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiQueueResponse(rsp)
}

// GetApiRelationsWithResponse request returning *GetApiRelationsResponse
func (c *ClientWithResponses) GetApiRelationsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiRelationsResponse, error) {
	rsp, err := c.GetApiRelations(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiRelationsResponse(rsp)
}

// PostApiRunsWithBodyWithResponse request with arbitrary body returning *PostApiRunsResponse
func (c *ClientWithResponses) PostApiRunsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiRunsResponse, error) {
	rsp, err := c.PostApiRunsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiRunsResponse(rsp)
}

func (c *ClientWithResponses) PostApiRunsWithResponse(ctx context.Context, body PostApiRunsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiRunsResponse, error) {
	rsp, err := c.PostApiRuns(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiRunsResponse(rsp)
}

// ParseGetApiEdgesResponse parses an HTTP response from a GetApiEdgesWithResponse call
func ParseGetApiEdgesResponse(rsp *http.Response) (*GetApiEdgesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiEdgesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListEdgesResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiEdgesIdResponse parses an HTTP response from a GetApiEdgesIdWithResponse call
func ParseGetApiEdgesIdResponse(rsp *http.Response) (*GetApiEdgesIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiEdgesIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EdgeResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiEdgesIdProvenanceResponse parses an HTTP response from a GetApiEdgesIdProvenanceWithResponse call
func ParseGetApiEdgesIdProvenanceResponse(rsp *http.Response) (*GetApiEdgesIdProvenanceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiEdgesIdProvenanceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EdgeProvenanceResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiEntitiesResponse parses an HTTP response from a GetApiEntitiesWithResponse call
func ParseGetApiEntitiesResponse(rsp *http.Response) (*GetApiEntitiesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiEntitiesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SearchEntitiesResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiEntitiesIdResponse parses an HTTP response from a GetApiEntitiesIdWithResponse call
func ParseGetApiEntitiesIdResponse(rsp *http.Response) (*GetApiEntitiesIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiEntitiesIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetEntityResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiEntitiesIdTimelineResponse parses an HTTP response from a GetApiEntitiesIdTimelineWithResponse call
func ParseGetApiEntitiesIdTimelineResponse(rsp *http.Response) (*GetApiEntitiesIdTimelineResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiEntitiesIdTimelineResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetEntityTimelineResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiNodesResponse parses an HTTP response from a GetApiNodesWithResponse call
func ParseGetApiNodesResponse(rsp *http.Response) (*GetApiNodesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiNodesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListNodesResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostApiNodesResponse parses an HTTP response from a PostApiNodesWithResponse call
func ParsePostApiNodesResponse(rsp *http.Response) (*PostApiNodesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiNodesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetApiNodesIdResponse parses an HTTP response from a GetApiNodesIdWithResponse call
func ParseGetApiNodesIdResponse(rsp *http.Response) (*GetApiNodesIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiNodesIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NodeResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiNodesIdContentResponse parses an HTTP response from a GetApiNodesIdContentWithResponse call
func ParseGetApiNodesIdContentResponse(rsp *http.Response) (*GetApiNodesIdContentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiNodesIdContentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetApiNodesIdEdgesResponse parses an HTTP response from a GetApiNodesIdEdgesWithResponse call
func ParseGetApiNodesIdEdgesResponse(rsp *http.Response) (*GetApiNodesIdEdgesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiNodesIdEdgesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetNodeEdgesResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiNodesIdProvenanceResponse parses an HTTP response from a GetApiNodesIdProvenanceWithResponse call
func ParseGetApiNodesIdProvenanceResponse(rsp *http.Response) (*GetApiNodesIdProvenanceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiNodesIdProvenanceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProvenanceSubgraph
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiQueueResponse parses an HTTP response from a GetApiQueueWithResponse call
func ParseGetApiQueueResponse(rsp *http.Response) (*GetApiQueueResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiQueueResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetQueueResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiRelationsResponse parses an HTTP response from a GetApiRelationsWithResponse call
func ParseGetApiRelationsResponse(rsp *http.Response) (*GetApiRelationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiRelationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListRelationsResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostApiRunsResponse parses an HTTP response from a PostApiRunsWithResponse call
func ParsePostApiRunsResponse(rsp *http.Response) (*PostApiRunsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiRunsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CreateRunResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
