//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes apiKeyAuthContextKey = "apiKeyAuth.Scopes"
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for EdgeInputDirection.
const (
	EdgeInputDirectionIncoming EdgeInputDirection = "incoming"
	EdgeInputDirectionOutgoing EdgeInputDirection = "outgoing"
)

// Valid indicates whether the value is a known member of the EdgeInputDirection enum.
func (e EdgeInputDirection) Valid() bool {
	switch e {
	case EdgeInputDirectionIncoming:
		return true
	case EdgeInputDirectionOutgoing:
		return true
	default:
		return false
	}
}

// Defines values for EdgeViewDirection.
const (
	EdgeViewDirectionIncoming EdgeViewDirection = "incoming"
	EdgeViewDirectionOutgoing EdgeViewDirection = "outgoing"
)

// Valid indicates whether the value is a known member of the EdgeViewDirection enum.
func (e EdgeViewDirection) Valid() bool {
	switch e {
	case EdgeViewDirectionIncoming:
		return true
	case EdgeViewDirectionOutgoing:
		return true
	default:
		return false
	}
}

// Branch defines model for Branch.
type Branch struct {
	// Contributor Contributor of the head claim.
	Contributor string `json:"contributor"`
	Head        string `json:"head"`

	// History Number of head revisions recorded for this branch.
	History int    `json:"history"`
	Name    string `json:"name"`

	// Time Time the head was recorded.
	Time time.Time `json:"time"`
}

// BranchList defines model for BranchList.
type BranchList struct {
	Branches []BranchSummary `json:"branches"`
}

// BranchSummary defines model for BranchSummary.
type BranchSummary struct {
	// Head The content-addressed head claim id.
	Head string `json:"head"`
	Name string `json:"name"`
}

// Claim defines model for Claim.
type Claim struct {
	// Canonical The canonical signed bytes (base64); verify the claim independently from these.
	Canonical   []byte     `json:"canonical"`
	ContentHash string     `json:"content_hash"`
	Contributor string     `json:"contributor"`
	CreatedAt   time.Time  `json:"created_at"`
	Edges       []EdgeView `json:"edges"`
	Encoding    string     `json:"encoding"`

	// Id Content-addressed claim id.
	Id string `json:"id"`

	// Node Content-addressed node id.
	Node string `json:"node"`
	Type string `json:"type"`
}

// Contribution The content of a claim to contribute. The server adds the contributor and signature.
type Contribution struct {
	Edges *[]EdgeInput `json:"edges,omitempty"`
	Node  NodeInput    `json:"node"`
}

// EdgeInput defines model for EdgeInput.
type EdgeInput struct {
	// Direction Relation direction from this node's perspective.
	Direction *EdgeInputDirection `json:"direction,omitempty"`

	// Reference The id of an existing node this edge points at.
	Reference string `json:"reference"`

	// Type The relation type.
	Type string `json:"type"`
}

// EdgeInputDirection Relation direction from this node's perspective.
type EdgeInputDirection string

// EdgeView defines model for EdgeView.
type EdgeView struct {
	Direction EdgeViewDirection `json:"direction"`
	Reference string            `json:"reference"`
	Type      string            `json:"type"`
}

// EdgeViewDirection defines model for EdgeView.Direction.
type EdgeViewDirection string

// Error defines model for Error.
type Error struct {
	// Error Human-readable message.
	Error string `json:"error"`

	// Subject On 403, the subject id to grant in config.
	Subject *string `json:"subject,omitempty"`
}

// Health defines model for Health.
type Health struct {
	// Signer The contributor identity this stack signs with.
	Signer *string `json:"signer,omitempty"`
	Status string  `json:"status"`
}

// NodeInput defines model for NodeInput.
type NodeInput struct {
	// Content The node's content, base64-encoded.
	Content []byte `json:"content"`

	// Encoding The content encoding.
	Encoding string `json:"encoding"`

	// Type The node type, application-defined (e.g. person, fruit).
	Type string `json:"type"`
}

// Query defines model for Query.
type Query struct {
	// Parameters Optional named query parameters.
	Parameters *map[string]interface{} `json:"parameters,omitempty"`

	// Query A read-only Cypher query.
	Query string `json:"query"`
}

// QueryResult defines model for QueryResult.
type QueryResult struct {
	Columns []string `json:"columns"`

	// Rows Row-major result; each row aligns with columns.
	Rows [][]interface{} `json:"rows"`
}

// Verification defines model for Verification.
type Verification struct {
	Branch string `json:"branch"`

	// Checked Number of claims verified.
	Checked int `json:"checked"`

	// Failures Ids of claims that failed verification (empty when ok).
	Failures *[]string `json:"failures,omitempty"`
	Head     string    `json:"head"`

	// Ok True if every checked claim verified.
	Ok bool `json:"ok"`
}

// BranchName defines model for BranchName.
type BranchName = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// apiKeyAuthContextKey is the context key for apiKeyAuth security scheme
type apiKeyAuthContextKey string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ContributeJSONRequestBody defines body for Contribute for application/json ContentType.
type ContributeJSONRequestBody = Contribution

// QueryJSONRequestBody defines body for Query for application/json ContentType.
type QueryJSONRequestBody = Query

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List branches
	// (GET /branches)
	ListBranches(w http.ResponseWriter, r *http.Request)
	// Get one branch
	// (GET /branches/{name})
	GetBranch(w http.ResponseWriter, r *http.Request, name BranchName)
	// Contribute a claim
	// (POST /branches/{name}/claims)
	Contribute(w http.ResponseWriter, r *http.Request, name BranchName)
	// Verify a branch
	// (GET /branches/{name}/verification)
	VerifyBranch(w http.ResponseWriter, r *http.Request, name BranchName)
	// Get a claim by id
	// (GET /claims/{id})
	GetClaim(w http.ResponseWriter, r *http.Request, id string)
	// Cypher query (read-only)
	// (POST /gql)
	Query(w http.ResponseWriter, r *http.Request)
	// Liveness and readiness of the stack
	// (GET /health)
	Health(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListBranches operation middleware
func (siw *ServerInterfaceWrapper) ListBranches(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBranches(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBranch operation middleware
func (siw *ServerInterfaceWrapper) GetBranch(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name BranchName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBranch(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Contribute operation middleware
func (siw *ServerInterfaceWrapper) Contribute(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name BranchName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Contribute(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyBranch operation middleware
func (siw *ServerInterfaceWrapper) VerifyBranch(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name BranchName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyBranch(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetClaim operation middleware
func (siw *ServerInterfaceWrapper) GetClaim(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetClaim(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Query operation middleware
func (siw *ServerInterfaceWrapper) Query(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Query(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Health(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/branches", wrapper.ListBranches)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/branches/{name}", wrapper.GetBranch)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/branches/{name}/claims", wrapper.Contribute)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/branches/{name}/verification", wrapper.VerifyBranch)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/claims/{id}", wrapper.GetClaim)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/gql", wrapper.Query)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.Health)

	return m
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type ForbiddenJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type ListBranchesRequestObject struct {
}

type ListBranchesResponseObject interface {
	VisitListBranchesResponse(w http.ResponseWriter) error
}

type ListBranches200JSONResponse BranchList

func (response ListBranches200JSONResponse) VisitListBranchesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListBranches401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListBranches401JSONResponse) VisitListBranchesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListBranches403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListBranches403JSONResponse) VisitListBranchesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetBranchRequestObject struct {
	Name BranchName `json:"name"`
}

type GetBranchResponseObject interface {
	VisitGetBranchResponse(w http.ResponseWriter) error
}

type GetBranch200JSONResponse Branch

func (response GetBranch200JSONResponse) VisitGetBranchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetBranch401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetBranch401JSONResponse) VisitGetBranchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetBranch403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetBranch403JSONResponse) VisitGetBranchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetBranch404JSONResponse struct{ NotFoundJSONResponse }

func (response GetBranch404JSONResponse) VisitGetBranchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ContributeRequestObject struct {
	Name BranchName `json:"name"`
	Body *ContributeJSONRequestBody
}

type ContributeResponseObject interface {
	VisitContributeResponse(w http.ResponseWriter) error
}

type Contribute201JSONResponse Claim

func (response Contribute201JSONResponse) VisitContributeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type Contribute400JSONResponse struct{ BadRequestJSONResponse }

func (response Contribute400JSONResponse) VisitContributeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Contribute401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Contribute401JSONResponse) VisitContributeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Contribute403JSONResponse struct{ ForbiddenJSONResponse }

func (response Contribute403JSONResponse) VisitContributeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type Contribute404JSONResponse struct{ NotFoundJSONResponse }

func (response Contribute404JSONResponse) VisitContributeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type Contribute409JSONResponse struct{ ConflictJSONResponse }

func (response Contribute409JSONResponse) VisitContributeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyBranchRequestObject struct {
	Name BranchName `json:"name"`
}

type VerifyBranchResponseObject interface {
	VisitVerifyBranchResponse(w http.ResponseWriter) error
}

type VerifyBranch200JSONResponse Verification

func (response VerifyBranch200JSONResponse) VisitVerifyBranchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyBranch401JSONResponse struct{ UnauthorizedJSONResponse }

func (response VerifyBranch401JSONResponse) VisitVerifyBranchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyBranch403JSONResponse struct{ ForbiddenJSONResponse }

func (response VerifyBranch403JSONResponse) VisitVerifyBranchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyBranch404JSONResponse struct{ NotFoundJSONResponse }

func (response VerifyBranch404JSONResponse) VisitVerifyBranchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetClaimRequestObject struct {
	Id string `json:"id"`
}

type GetClaimResponseObject interface {
	VisitGetClaimResponse(w http.ResponseWriter) error
}

type GetClaim200JSONResponse Claim

func (response GetClaim200JSONResponse) VisitGetClaimResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetClaim401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetClaim401JSONResponse) VisitGetClaimResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetClaim403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetClaim403JSONResponse) VisitGetClaimResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetClaim404JSONResponse struct{ NotFoundJSONResponse }

func (response GetClaim404JSONResponse) VisitGetClaimResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type QueryRequestObject struct {
	Body *QueryJSONRequestBody
}

type QueryResponseObject interface {
	VisitQueryResponse(w http.ResponseWriter) error
}

type Query200JSONResponse QueryResult

func (response Query200JSONResponse) VisitQueryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Query401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Query401JSONResponse) VisitQueryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Query403JSONResponse struct{ ForbiddenJSONResponse }

func (response Query403JSONResponse) VisitQueryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type Query501JSONResponse Error

func (response Query501JSONResponse) VisitQueryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

type HealthRequestObject struct {
}

type HealthResponseObject interface {
	VisitHealthResponse(w http.ResponseWriter) error
}

type Health200JSONResponse Health

func (response Health200JSONResponse) VisitHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List branches
	// (GET /branches)
	ListBranches(ctx context.Context, request ListBranchesRequestObject) (ListBranchesResponseObject, error)
	// Get one branch
	// (GET /branches/{name})
	GetBranch(ctx context.Context, request GetBranchRequestObject) (GetBranchResponseObject, error)
	// Contribute a claim
	// (POST /branches/{name}/claims)
	Contribute(ctx context.Context, request ContributeRequestObject) (ContributeResponseObject, error)
	// Verify a branch
	// (GET /branches/{name}/verification)
	VerifyBranch(ctx context.Context, request VerifyBranchRequestObject) (VerifyBranchResponseObject, error)
	// Get a claim by id
	// (GET /claims/{id})
	GetClaim(ctx context.Context, request GetClaimRequestObject) (GetClaimResponseObject, error)
	// Cypher query (read-only)
	// (POST /gql)
	Query(ctx context.Context, request QueryRequestObject) (QueryResponseObject, error)
	// Liveness and readiness of the stack
	// (GET /health)
	Health(ctx context.Context, request HealthRequestObject) (HealthResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListBranches operation middleware
func (sh *strictHandler) ListBranches(w http.ResponseWriter, r *http.Request) {
	var request ListBranchesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListBranches(ctx, request.(ListBranchesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListBranches")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListBranchesResponseObject); ok {
		if err := validResponse.VisitListBranchesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetBranch operation middleware
func (sh *strictHandler) GetBranch(w http.ResponseWriter, r *http.Request, name BranchName) {
	var request GetBranchRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBranch(ctx, request.(GetBranchRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBranch")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBranchResponseObject); ok {
		if err := validResponse.VisitGetBranchResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Contribute operation middleware
func (sh *strictHandler) Contribute(w http.ResponseWriter, r *http.Request, name BranchName) {
	var request ContributeRequestObject

	request.Name = name

	var body ContributeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Contribute(ctx, request.(ContributeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Contribute")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ContributeResponseObject); ok {
		if err := validResponse.VisitContributeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// VerifyBranch operation middleware
func (sh *strictHandler) VerifyBranch(w http.ResponseWriter, r *http.Request, name BranchName) {
	var request VerifyBranchRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.VerifyBranch(ctx, request.(VerifyBranchRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VerifyBranch")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VerifyBranchResponseObject); ok {
		if err := validResponse.VisitVerifyBranchResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetClaim operation middleware
func (sh *strictHandler) GetClaim(w http.ResponseWriter, r *http.Request, id string) {
	var request GetClaimRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetClaim(ctx, request.(GetClaimRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetClaim")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetClaimResponseObject); ok {
		if err := validResponse.VisitGetClaimResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Query operation middleware
func (sh *strictHandler) Query(w http.ResponseWriter, r *http.Request) {
	var request QueryRequestObject

	var body QueryJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Query(ctx, request.(QueryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Query")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(QueryResponseObject); ok {
		if err := validResponse.VisitQueryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Health operation middleware
func (sh *strictHandler) Health(w http.ResponseWriter, r *http.Request) {
	var request HealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Health(ctx, request.(HealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Health")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthResponseObject); ok {
		if err := validResponse.VisitHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fptjxu38f8qg/3/gUjCSjrXToCeX9mGkzgPbuo4SQHLyFHLkUTfLrkmuXfeGAcUfdnX/YT5JMUMuU+n",
	"1enc+ozm1d1qyeE8z2+G+z7JTFEajdq75PR9UgorCvRo+emxFTrbPRcF0pNEl1lVemV0cpq83CGs+T1o",
	"UeAiSRNFv5fC75I00bwp/EkTi28rZVEmp95WmCYu22EhiKivS1rnvFV6m1xdXdFiVxrtMLAg5At8W6Hz",
	"9JQZ7VHzv6Isc5UJ4mb5xhFL73tk/9/iJjlN/m/ZibcMb93yqbXGhqP2RbLhMLgUDgqRb4wtUC6SqzR5",
	"YvQmV9kn4oNOsGpd0U/0wEc7uFR+B57eV9ai9rBDEdj70ti1khL1p+HPVes3mHnIRXbumKPGxpCJUqxV",
	"rny9APYSI2vIhLUKeeVKN5uVBGdAaDAlWuGNhUxo2FqhPSgPKkiutjAxem2ElUpvp4uVJnmfG/+lqbS8",
	"e3GfG3BVtmu8nbjMhSpY6z9pUfmdseo3/AScPKr8DrWPVEG5TunGwkaonH31qgmwXhBzcFvSs1chsloP",
	"M3Y/up90L8Fs2L7kaY3k6fW4TRN6PRLQabJTzhtb75/xvCrWyOSZtMUL5ZTRJFRmrEQJG2PB75SLqu+d",
	"q7THLVqir2N62jvYq9G8pQrs5KEwb44j8hTvwieniRQe50xhT9arfj571aQ4lr+TNh3oNzLzuqVlOACI",
	"y2Ce71RIcEMTBbHD/8pj4Y55TiD2Y1UUwtasg3CcsFbUe5y35A/z1ZDaY60x93jmQu3nQkqLzqHseQ4o",
	"Oeo8B2x4g6bHWH5CR4w4utBGq0zkB/htXoNTW40S1rVHB5O1cPjFg+lDuECrNnXIukEILbFELVH7vIaN",
	"NQW9dDhwIKIyJmpUz6874XajbnstLvffWxQe5a+CHeY2DpsmKLcf4EVP5RZ/Vni570BpgjozlIZHWVNy",
	"PJMM3eFmTzASb0OE1h2iEX445k2KwpWPizt6wl0z00Dp1yM76Dbtudmob/bq+Y1xQ/lQRB150+EADMXU",
	"ob1AC0LKUHV7vIDQkn1Y+MqyMw7j4MOd4JkuKz/mBY2VbiLw3MiGwPU4pt1jSurO3AtiqSxmnfI2osrJ",
	"603ltyZYbKjRF5iHItlubAJVOXaezxyUaF1JLy9YW6irgtjr0VQ6MwX9+3rEzSxu0KLODoBjJdmUGvCd",
	"cl7pbfBZZoBMAaVR2jsQ/kYnHoOoUTRawoy/E0WZ0/ZcnbMv3uz5HeNx5SFbcBK42RT/ldL+w8jd4z/t",
	"8TQqCwOqPUGw+Xmo46+rQui5RSHFOkco0DmxxVEjRSC7T+MvGh6c3E85RHto15sG3TbQdnHUWoHLMbG+",
	"RpH7EWTHdcwezjJNvlBUwZSvg086L7Jzzh+hzRh6llTy9Bzr09+++P58sRhXhhe+Coptt5nzo/LFbWMC",
	"dilkFL1GoL0vZIzvuCaFUMrnnN6v4bxDZbpf5w7n6mbVUFd7yP+DwjtkibrEFHqE5hI3itDJBBfbBacu",
	"o1PY2Er56fD48O6o3g/WvFFT/LXCMRg4nBcIKRUxK/IfeqtCy38tPsqwjmcHEt4SdeiI9fyrY+Ftw8K1",
	"pggoVOdG5zU8qcsd2kDueGQFggelfYGOi8y+6+VVoYeV9IB9u4ppzaXb5/2FuZwX4o2xYPmwh4Ai24E1",
	"lyDyNhIhnsgzlubE5p+Rs24E/Q33kaUx6X8mwBv97lBTMg5Nd5ido7yp1WNg4wKmVijHWzrqZCuLIwp7",
	"Jl2Pit8JH9veSDF2xhMsSl/D5Q41mPPpQHFHTXWwkzXnIxFrKwS1AbwgD44KiPBtRMi1MTkKfaAV69pI",
	"zpuNOvdtRNkWs8oqX/9IcCuoSpTqW6wfVaEmDPn8iUAz64NLEuX6zxyIyu+gYCjt4EyU6hzrswVMvqef",
	"zrSh92egttpYdJBZ5IohcreYNvM+YhhtN/H72/zRD8/m32LdCR34Ig2uUVi0DYfh6csmFX/zy8s9GHcb",
	"tt9c+jNSMQNPVjLT7c7feV+GcYrSGzMShU9/fAmPfnjG8wYBTultjjCbWaHPcS7Xs1k4+bSHxptmMXoi",
	"QW9KQytNfAbDM3rYWlHyxK4m6sVipVf6UYPid8Z5B/hOZNRIzmZGRxlnsxRyUVF3LgNuFc0obKNyhN//",
	"/i+iaUkBK60NeNQEK4h/m+3UBYI1FYNOFVRXCr9zC9ifIAWylSVuV3qiiYclfPPLS1iyTs6xnj6EZsrV",
	"bWuHfHOqrjIkKlIeVaGVzoX3KmMtUvf/+z//AZdWeeT/hCyUns1OSRkA87hoNgMWLBSDZjiRRhWnYCs9",
	"iPK0Sfe02TWU+JTZjCn1zBWINIsiA7yotOpC5bhFGceQPIOaWGQjySkx+SRa2ZJA+wOOpvFCOZst4BFk",
	"uSJ0MOvOd7Mw+Rxp8iYilPwyrxwoH5oDN30YPD44SkBlyrfz35VuYqGxH0YWLEz8AZw3ZUZFWaKWRG0B",
	"TylrrXTsyB1Y9JXVjTWZmWKNUqIkuUcHJeSqPMStV7qZ3BOp4ZCkFxGkc03pEgq0mNc8f9PO2yrztGCx",
	"YuyiPIOZJgbJF5M0uUDrQtCeLO4tTjgrl6hFqZLT5P7iZHGf2l7ydQrzZX+AtsURtPiCBXYxfccJbyv8",
	"YMgOL0K+dnBGDscpp3WYZzI5Tb5Tzj9uTrx2j/Gnk5OPNh/ujQwPTOcbuUP0N+CeJ9YPTu4dot8yvByM",
	"tXnT/eObuhsIrk/N5JDV0nJEphVbF9o4IZPXtLa10/I9VZGrg+bqZPvMsVXSvqOn4FVBsFl302TITKX9",
	"LYz3FUbb3b3lbrbap7MS7XhwfEd70zI061fogYpFC12u2TUdNAevxk/plix7l41Xr0ecYhlS+PWu4wMJ",
	"p0lpnL/hwgNZqHb+5lu7nEJM1BNKDaFBa5on9rk2u09DLhe6Drmc6AyGQG4wywvJvR0vr3R7ydfk+JjY",
	"h9k7BSEvhM6IaMdlyFUr3SS2cDNHvQWt64OWfkxw0TxjcPKUOW5HLIFfWBM8UZKS/eVOZTsoKudB5GTr",
	"Ogi3gJcG1pXKJQgqBXFIlatzhFUickIDPJ/ithZXSdqvz8SnF3aLPih5o6zz6UpnovQV4RzvQMl22A6N",
	"e/KIRV+n5ExlI++czVda6DB084YL3+Sx8NkOliC8KVQ2d9U6ILXBvatyIEBirtaUKXClqdYAXxDTa6pk",
	"DsOJUrmscpxxtPHoFlMuY8Mc0zlZvBNH5x8bWX+0/DKYMl8Nmwxqw6/2ctu9j3c2374cus7meLoUrmep",
	"Pm6KSe/keDbqfRDwP5snacOfj29ovygYJtZeKooYsZdcOVLHq+by4lrfPo54Ku1gU+X5sGM2lIl8v7zG",
	"zmbS3ii4tJl7rfROOMbmZMEsN66yOI11tzTW9/POfu0diQweOdR3X4AHo40DvjrQS5ThD1KTgxpB3F1R",
	"Dl6xfK/k1VFQ3Za0FJTO8kpyP9pvKsZbituhtScxMu7MV44ntD8SVGvazXUNfPN5zDFuc7Hfv8kd+fiL",
	"z7n9p1/sX9u3fE0/DtJeVBrEgXEviK1Q2nn2Oq7lC/i+8u3AglvOlcZ3ZWRe6WY/jwq6Dp9JxwtfuFAC",
	"zrqadcaLGYitdDjXrBnHBXefzXiaA04UhGFyjxZslVObDMKBFp5nMyikg4k2K+2qEq1DiU0rI6TKPD0Z",
	"C6byc7OZxwQbeZyOJdQO8J19fnLvDNSmuR1uhwPeWLFFWIvsHLWE0poLRdBOm6gHYsZuRIYwYRWwEueR",
	"5bjNhU+hSBQ0D96ANNOxdB5uC+4G4wTatwI3Jx/30HghcCAjBG/49PXi84+I4Y59ktg4U+NEO9HzH4ju",
	"s7iOZ/pROmmjdzo+Cti1l5qxtgw9K9553qGp4wmHvnvkW1LloCoXgzl8cvrq9XDqcYEaXTcaVvwUP6Zj",
	"Mj0FuNp5LEgFQ5LvByPzV6+v0uGY/9VramlDIxnydmXz5DRZUrn+dwAAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
