//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for VerificationFailureMode.
const (
	CorruptBytes   VerificationFailureMode = "corrupt-bytes"
	InvalidContent VerificationFailureMode = "invalid-content"
)

// Valid indicates whether the value is a known member of the VerificationFailureMode enum.
func (e VerificationFailureMode) Valid() bool {
	switch e {
	case CorruptBytes:
		return true
	case InvalidContent:
		return true
	default:
		return false
	}
}

// Defines values for VerificationReportStatus.
const (
	VerificationReportStatusComplete VerificationReportStatus = "complete"
	VerificationReportStatusError    VerificationReportStatus = "error"
	VerificationReportStatusRunning  VerificationReportStatus = "running"
	VerificationReportStatusStopped  VerificationReportStatus = "stopped"
)

// Valid indicates whether the value is a known member of the VerificationReportStatus enum.
func (e VerificationReportStatus) Valid() bool {
	switch e {
	case VerificationReportStatusComplete:
		return true
	case VerificationReportStatusError:
		return true
	case VerificationReportStatusRunning:
		return true
	case VerificationReportStatusStopped:
		return true
	default:
		return false
	}
}

// BranchList defines model for BranchList.
type BranchList struct {
	Branches []BranchSummary `json:"branches"`
}

// BranchSummary defines model for BranchSummary.
type BranchSummary struct {
	// Head The content-addressed head claim id.
	Head string `json:"head"`
	Name string `json:"name"`
}

// ContributionResult The result of a contribution transaction — the ids (handles) of the appended claims.
type ContributionResult struct {
	// Ids Content-addressed ids of the contributed claims, in order.
	Ids []string `json:"ids"`
}

// Error defines model for Error.
type Error struct {
	// Error Human-readable message.
	Error string `json:"error"`

	// Subject On 403, the subject id to grant in config.
	Subject *string `json:"subject,omitempty"`
}

// GqlQuery defines model for GqlQuery.
type GqlQuery struct {
	// Parameters Optional named query parameters.
	Parameters *map[string]interface{} `json:"parameters,omitempty"`

	// Query A read-only Cypher query.
	Query string `json:"query"`
}

// GqlResult defines model for GqlResult.
type GqlResult struct {
	Columns []string `json:"columns"`

	// Rows Row-major result; each row aligns with columns.
	Rows [][]interface{} `json:"rows"`
}

// Health defines model for Health.
type Health struct {
	// Signer The contributor identity this stack signs with.
	Signer *string `json:"signer,omitempty"`
	Status string  `json:"status"`
}

// StorageLayer defines model for StorageLayer.
type StorageLayer struct {
	Name string `json:"name"`

	// Type Adapter type (e.g. memory, filesystem, s3, postgres, neo4j).
	Type string `json:"type"`
}

// StorageLayerList defines model for StorageLayerList.
type StorageLayerList struct {
	// Layers Read-through tiers, top (cache) to bottom (authoritative).
	Layers []StorageLayer `json:"layers"`
}

// VerificationConfig Parameters for a verification run — the same shape whether declared in
// the stack config (scheduled/automatic) or posted ad-hoc.
type VerificationConfig struct {
	// Closure Root of the closure to verify — a branch name or a claim id.
	Closure string `json:"closure"`

	// ContentThreshold Max content size, in bytes, to re-read and re-hash per claim. Larger
	// content is skipped this run (the claim's signature is still checked).
	// Omit to verify all content regardless of size.
	ContentThreshold *int `json:"contentThreshold,omitempty"`

	// Layer Storage layer (by name) to read directly. Omit to read the composed
	// read-through view — which may mask the loss of an object on a deeper
	// layer, so name a layer to verify it without blind spots.
	Layer *string `json:"layer,omitempty"`
}

// VerificationFailure defines model for VerificationFailure.
type VerificationFailure struct {
	Detail *string `json:"detail,omitempty"`

	// Id The claim or object id that failed.
	Id string `json:"id"`

	// Layer The layer where the failure was observed.
	Layer string `json:"layer"`

	// Mode corrupt-bytes — stored bytes don't match their hash (storage rot/loss;
	// self-heals via read-through if a deeper layer is intact).
	// invalid-content — the claim itself doesn't validate (e.g. bad
	// signature); unrepairable.
	Mode VerificationFailureMode `json:"mode"`
}

// VerificationFailureMode corrupt-bytes — stored bytes don't match their hash (storage rot/loss;
// self-heals via read-through if a deeper layer is intact).
// invalid-content — the claim itself doesn't validate (e.g. bad
// signature); unrepairable.
type VerificationFailureMode string

// VerificationReport A point-in-time record of a verification run; embeds the config that produced it.
type VerificationReport struct {
	BytesRead     *int       `json:"bytesRead,omitempty"`
	ClaimsChecked *int       `json:"claimsChecked,omitempty"`
	CompletedAt   *time.Time `json:"completedAt,omitempty"`

	// Config Parameters for a verification run — the same shape whether declared in
	// the stack config (scheduled/automatic) or posted ad-hoc.
	Config   VerificationConfig     `json:"config"`
	Failures *[]VerificationFailure `json:"failures,omitempty"`
	Id       string                 `json:"id"`

	// Ok True when no failures were found in this run.
	Ok        bool                     `json:"ok"`
	StartedAt time.Time                `json:"startedAt"`
	Status    VerificationReportStatus `json:"status"`
}

// VerificationReportStatus defines model for VerificationReport.Status.
type VerificationReportStatus string

// VerificationReportList defines model for VerificationReportList.
type VerificationReportList struct {
	Reports []VerificationReport `json:"reports"`
}

// BranchName defines model for BranchName.
type BranchName = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GqlJSONRequestBody defines body for Gql for application/json ContentType.
type GqlJSONRequestBody = GqlQuery

// StartVerificationJSONRequestBody defines body for StartVerification for application/json ContentType.
type StartVerificationJSONRequestBody = VerificationConfig

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List branch names with their current head
	// (GET /branches)
	ListBranches(w http.ResponseWriter, r *http.Request)
	// Contribute a set of claims (bulk)
	// (POST /branches/{name}/claims)
	Contribute(w http.ResponseWriter, r *http.Request, name BranchName)
	// Fetch a claim within a branch's closure
	// (GET /branches/{name}/claims/{id})
	GetClaim(w http.ResponseWriter, r *http.Request, name BranchName, id string)
	// Contribute a single claim
	// (PUT /branches/{name}/claims/{id})
	PutClaim(w http.ResponseWriter, r *http.Request, name BranchName, id string)
	// Fetch content bytes within a branch's closure
	// (GET /branches/{name}/contents/{hash})
	GetContent(w http.ResponseWriter, r *http.Request, name BranchName, hash string)
	// Cypher query over a branch (optional)
	// (POST /branches/{name}/gql)
	Gql(w http.ResponseWriter, r *http.Request, name BranchName)
	// Liveness and readiness of the stack
	// (GET /health)
	Health(w http.ResponseWriter, r *http.Request)
	// List storage layers
	// (GET /storage/layers)
	ListStorageLayers(w http.ResponseWriter, r *http.Request)
	// List verification runs
	// (GET /verification)
	ListVerifications(w http.ResponseWriter, r *http.Request)
	// Start a verification run
	// (POST /verification)
	StartVerification(w http.ResponseWriter, r *http.Request)
	// Stop a verification run
	// (DELETE /verification/{reportId})
	StopVerification(w http.ResponseWriter, r *http.Request, reportId string)
	// Show a verification run
	// (GET /verification/{reportId})
	GetVerification(w http.ResponseWriter, r *http.Request, reportId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListBranches operation middleware
func (siw *ServerInterfaceWrapper) ListBranches(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBranches(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Contribute operation middleware
func (siw *ServerInterfaceWrapper) Contribute(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name BranchName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Contribute(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetClaim operation middleware
func (siw *ServerInterfaceWrapper) GetClaim(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name BranchName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetClaim(w, r, name, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutClaim operation middleware
func (siw *ServerInterfaceWrapper) PutClaim(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name BranchName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutClaim(w, r, name, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetContent operation middleware
func (siw *ServerInterfaceWrapper) GetContent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name BranchName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Path parameter "hash" -------------
	var hash string

	err = runtime.BindStyledParameterWithOptions("simple", "hash", r.PathValue("hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetContent(w, r, name, hash)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Gql operation middleware
func (siw *ServerInterfaceWrapper) Gql(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "name" -------------
	var name BranchName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Gql(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Health(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListStorageLayers operation middleware
func (siw *ServerInterfaceWrapper) ListStorageLayers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListStorageLayers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListVerifications operation middleware
func (siw *ServerInterfaceWrapper) ListVerifications(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVerifications(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartVerification operation middleware
func (siw *ServerInterfaceWrapper) StartVerification(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartVerification(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopVerification operation middleware
func (siw *ServerInterfaceWrapper) StopVerification(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "reportId" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "reportId", r.PathValue("reportId"), &reportId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "reportId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopVerification(w, r, reportId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVerification operation middleware
func (siw *ServerInterfaceWrapper) GetVerification(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "reportId" -------------
	var reportId string

	err = runtime.BindStyledParameterWithOptions("simple", "reportId", r.PathValue("reportId"), &reportId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "reportId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVerification(w, r, reportId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/branches", wrapper.ListBranches)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/branches/{name}/claims", wrapper.Contribute)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/branches/{name}/claims/{id}", wrapper.GetClaim)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/branches/{name}/claims/{id}", wrapper.PutClaim)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/branches/{name}/contents/{hash}", wrapper.GetContent)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/branches/{name}/gql", wrapper.Gql)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.Health)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/storage/layers", wrapper.ListStorageLayers)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/verification", wrapper.ListVerifications)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/verification", wrapper.StartVerification)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/verification/{reportId}", wrapper.StopVerification)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/verification/{reportId}", wrapper.GetVerification)

	return m
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type ForbiddenJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type ListBranchesRequestObject struct {
}

type ListBranchesResponseObject interface {
	VisitListBranchesResponse(w http.ResponseWriter) error
}

type ListBranches200JSONResponse BranchList

func (response ListBranches200JSONResponse) VisitListBranchesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListBranches401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListBranches401JSONResponse) VisitListBranchesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListBranches403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListBranches403JSONResponse) VisitListBranchesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ContributeRequestObject struct {
	Name BranchName `json:"name"`
	Body io.Reader
}

type ContributeResponseObject interface {
	VisitContributeResponse(w http.ResponseWriter) error
}

type Contribute201JSONResponse ContributionResult

func (response Contribute201JSONResponse) VisitContributeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type Contribute400JSONResponse struct{ BadRequestJSONResponse }

func (response Contribute400JSONResponse) VisitContributeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Contribute401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Contribute401JSONResponse) VisitContributeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Contribute403JSONResponse struct{ ForbiddenJSONResponse }

func (response Contribute403JSONResponse) VisitContributeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type Contribute404JSONResponse struct{ NotFoundJSONResponse }

func (response Contribute404JSONResponse) VisitContributeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type Contribute409JSONResponse struct{ ConflictJSONResponse }

func (response Contribute409JSONResponse) VisitContributeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetClaimRequestObject struct {
	Name BranchName `json:"name"`
	Id   string     `json:"id"`
}

type GetClaimResponseObject interface {
	VisitGetClaimResponse(w http.ResponseWriter) error
}

type GetClaim200ApplicationcborResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetClaim200ApplicationcborResponse) VisitGetClaimResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/cbor")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetClaim401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetClaim401JSONResponse) VisitGetClaimResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetClaim403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetClaim403JSONResponse) VisitGetClaimResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetClaim404JSONResponse struct{ NotFoundJSONResponse }

func (response GetClaim404JSONResponse) VisitGetClaimResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PutClaimRequestObject struct {
	Name BranchName `json:"name"`
	Id   string     `json:"id"`
	Body io.Reader
}

type PutClaimResponseObject interface {
	VisitPutClaimResponse(w http.ResponseWriter) error
}

type PutClaim204Response struct {
}

func (response PutClaim204Response) VisitPutClaimResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PutClaim400JSONResponse struct{ BadRequestJSONResponse }

func (response PutClaim400JSONResponse) VisitPutClaimResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PutClaim401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PutClaim401JSONResponse) VisitPutClaimResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PutClaim403JSONResponse struct{ ForbiddenJSONResponse }

func (response PutClaim403JSONResponse) VisitPutClaimResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type PutClaim404JSONResponse struct{ NotFoundJSONResponse }

func (response PutClaim404JSONResponse) VisitPutClaimResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PutClaim409JSONResponse struct{ ConflictJSONResponse }

func (response PutClaim409JSONResponse) VisitPutClaimResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetContentRequestObject struct {
	Name BranchName `json:"name"`
	Hash string     `json:"hash"`
}

type GetContentResponseObject interface {
	VisitGetContentResponse(w http.ResponseWriter) error
}

type GetContent200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetContent200ApplicationoctetStreamResponse) VisitGetContentResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetContent401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetContent401JSONResponse) VisitGetContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetContent403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetContent403JSONResponse) VisitGetContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetContent404JSONResponse struct{ NotFoundJSONResponse }

func (response GetContent404JSONResponse) VisitGetContentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GqlRequestObject struct {
	Name BranchName `json:"name"`
	Body *GqlJSONRequestBody
}

type GqlResponseObject interface {
	VisitGqlResponse(w http.ResponseWriter) error
}

type Gql200JSONResponse GqlResult

func (response Gql200JSONResponse) VisitGqlResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Gql401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Gql401JSONResponse) VisitGqlResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Gql403JSONResponse struct{ ForbiddenJSONResponse }

func (response Gql403JSONResponse) VisitGqlResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type Gql404JSONResponse struct{ NotFoundJSONResponse }

func (response Gql404JSONResponse) VisitGqlResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type Gql501JSONResponse Error

func (response Gql501JSONResponse) VisitGqlResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

type HealthRequestObject struct {
}

type HealthResponseObject interface {
	VisitHealthResponse(w http.ResponseWriter) error
}

type Health200JSONResponse Health

func (response Health200JSONResponse) VisitHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListStorageLayersRequestObject struct {
}

type ListStorageLayersResponseObject interface {
	VisitListStorageLayersResponse(w http.ResponseWriter) error
}

type ListStorageLayers200JSONResponse StorageLayerList

func (response ListStorageLayers200JSONResponse) VisitListStorageLayersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListStorageLayers401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListStorageLayers401JSONResponse) VisitListStorageLayersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListStorageLayers403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListStorageLayers403JSONResponse) VisitListStorageLayersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListVerificationsRequestObject struct {
}

type ListVerificationsResponseObject interface {
	VisitListVerificationsResponse(w http.ResponseWriter) error
}

type ListVerifications200JSONResponse VerificationReportList

func (response ListVerifications200JSONResponse) VisitListVerificationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListVerifications401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListVerifications401JSONResponse) VisitListVerificationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListVerifications403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListVerifications403JSONResponse) VisitListVerificationsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type StartVerificationRequestObject struct {
	Body *StartVerificationJSONRequestBody
}

type StartVerificationResponseObject interface {
	VisitStartVerificationResponse(w http.ResponseWriter) error
}

type StartVerification202JSONResponse VerificationReport

func (response StartVerification202JSONResponse) VisitStartVerificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type StartVerification400JSONResponse struct{ BadRequestJSONResponse }

func (response StartVerification400JSONResponse) VisitStartVerificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type StartVerification401JSONResponse struct{ UnauthorizedJSONResponse }

func (response StartVerification401JSONResponse) VisitStartVerificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type StartVerification403JSONResponse struct{ ForbiddenJSONResponse }

func (response StartVerification403JSONResponse) VisitStartVerificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type StopVerificationRequestObject struct {
	ReportId string `json:"reportId"`
}

type StopVerificationResponseObject interface {
	VisitStopVerificationResponse(w http.ResponseWriter) error
}

type StopVerification200JSONResponse VerificationReport

func (response StopVerification200JSONResponse) VisitStopVerificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type StopVerification401JSONResponse struct{ UnauthorizedJSONResponse }

func (response StopVerification401JSONResponse) VisitStopVerificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type StopVerification403JSONResponse struct{ ForbiddenJSONResponse }

func (response StopVerification403JSONResponse) VisitStopVerificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type StopVerification404JSONResponse struct{ NotFoundJSONResponse }

func (response StopVerification404JSONResponse) VisitStopVerificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetVerificationRequestObject struct {
	ReportId string `json:"reportId"`
}

type GetVerificationResponseObject interface {
	VisitGetVerificationResponse(w http.ResponseWriter) error
}

type GetVerification200JSONResponse VerificationReport

func (response GetVerification200JSONResponse) VisitGetVerificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVerification401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetVerification401JSONResponse) VisitGetVerificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetVerification403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetVerification403JSONResponse) VisitGetVerificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetVerification404JSONResponse struct{ NotFoundJSONResponse }

func (response GetVerification404JSONResponse) VisitGetVerificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List branch names with their current head
	// (GET /branches)
	ListBranches(ctx context.Context, request ListBranchesRequestObject) (ListBranchesResponseObject, error)
	// Contribute a set of claims (bulk)
	// (POST /branches/{name}/claims)
	Contribute(ctx context.Context, request ContributeRequestObject) (ContributeResponseObject, error)
	// Fetch a claim within a branch's closure
	// (GET /branches/{name}/claims/{id})
	GetClaim(ctx context.Context, request GetClaimRequestObject) (GetClaimResponseObject, error)
	// Contribute a single claim
	// (PUT /branches/{name}/claims/{id})
	PutClaim(ctx context.Context, request PutClaimRequestObject) (PutClaimResponseObject, error)
	// Fetch content bytes within a branch's closure
	// (GET /branches/{name}/contents/{hash})
	GetContent(ctx context.Context, request GetContentRequestObject) (GetContentResponseObject, error)
	// Cypher query over a branch (optional)
	// (POST /branches/{name}/gql)
	Gql(ctx context.Context, request GqlRequestObject) (GqlResponseObject, error)
	// Liveness and readiness of the stack
	// (GET /health)
	Health(ctx context.Context, request HealthRequestObject) (HealthResponseObject, error)
	// List storage layers
	// (GET /storage/layers)
	ListStorageLayers(ctx context.Context, request ListStorageLayersRequestObject) (ListStorageLayersResponseObject, error)
	// List verification runs
	// (GET /verification)
	ListVerifications(ctx context.Context, request ListVerificationsRequestObject) (ListVerificationsResponseObject, error)
	// Start a verification run
	// (POST /verification)
	StartVerification(ctx context.Context, request StartVerificationRequestObject) (StartVerificationResponseObject, error)
	// Stop a verification run
	// (DELETE /verification/{reportId})
	StopVerification(ctx context.Context, request StopVerificationRequestObject) (StopVerificationResponseObject, error)
	// Show a verification run
	// (GET /verification/{reportId})
	GetVerification(ctx context.Context, request GetVerificationRequestObject) (GetVerificationResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListBranches operation middleware
func (sh *strictHandler) ListBranches(w http.ResponseWriter, r *http.Request) {
	var request ListBranchesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListBranches(ctx, request.(ListBranchesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListBranches")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListBranchesResponseObject); ok {
		if err := validResponse.VisitListBranchesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Contribute operation middleware
func (sh *strictHandler) Contribute(w http.ResponseWriter, r *http.Request, name BranchName) {
	var request ContributeRequestObject

	request.Name = name

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Contribute(ctx, request.(ContributeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Contribute")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ContributeResponseObject); ok {
		if err := validResponse.VisitContributeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetClaim operation middleware
func (sh *strictHandler) GetClaim(w http.ResponseWriter, r *http.Request, name BranchName, id string) {
	var request GetClaimRequestObject

	request.Name = name
	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetClaim(ctx, request.(GetClaimRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetClaim")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetClaimResponseObject); ok {
		if err := validResponse.VisitGetClaimResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutClaim operation middleware
func (sh *strictHandler) PutClaim(w http.ResponseWriter, r *http.Request, name BranchName, id string) {
	var request PutClaimRequestObject

	request.Name = name
	request.Id = id

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutClaim(ctx, request.(PutClaimRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutClaim")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutClaimResponseObject); ok {
		if err := validResponse.VisitPutClaimResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetContent operation middleware
func (sh *strictHandler) GetContent(w http.ResponseWriter, r *http.Request, name BranchName, hash string) {
	var request GetContentRequestObject

	request.Name = name
	request.Hash = hash

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetContent(ctx, request.(GetContentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetContent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetContentResponseObject); ok {
		if err := validResponse.VisitGetContentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Gql operation middleware
func (sh *strictHandler) Gql(w http.ResponseWriter, r *http.Request, name BranchName) {
	var request GqlRequestObject

	request.Name = name

	var body GqlJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Gql(ctx, request.(GqlRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Gql")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GqlResponseObject); ok {
		if err := validResponse.VisitGqlResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Health operation middleware
func (sh *strictHandler) Health(w http.ResponseWriter, r *http.Request) {
	var request HealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Health(ctx, request.(HealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Health")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthResponseObject); ok {
		if err := validResponse.VisitHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListStorageLayers operation middleware
func (sh *strictHandler) ListStorageLayers(w http.ResponseWriter, r *http.Request) {
	var request ListStorageLayersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListStorageLayers(ctx, request.(ListStorageLayersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListStorageLayers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListStorageLayersResponseObject); ok {
		if err := validResponse.VisitListStorageLayersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListVerifications operation middleware
func (sh *strictHandler) ListVerifications(w http.ResponseWriter, r *http.Request) {
	var request ListVerificationsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListVerifications(ctx, request.(ListVerificationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListVerifications")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListVerificationsResponseObject); ok {
		if err := validResponse.VisitListVerificationsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartVerification operation middleware
func (sh *strictHandler) StartVerification(w http.ResponseWriter, r *http.Request) {
	var request StartVerificationRequestObject

	var body StartVerificationJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StartVerification(ctx, request.(StartVerificationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartVerification")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StartVerificationResponseObject); ok {
		if err := validResponse.VisitStartVerificationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StopVerification operation middleware
func (sh *strictHandler) StopVerification(w http.ResponseWriter, r *http.Request, reportId string) {
	var request StopVerificationRequestObject

	request.ReportId = reportId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StopVerification(ctx, request.(StopVerificationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StopVerification")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StopVerificationResponseObject); ok {
		if err := validResponse.VisitStopVerificationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVerification operation middleware
func (sh *strictHandler) GetVerification(w http.ResponseWriter, r *http.Request, reportId string) {
	var request GetVerificationRequestObject

	request.ReportId = reportId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVerification(ctx, request.(GetVerificationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVerification")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVerificationResponseObject); ok {
		if err := validResponse.VisitGetVerificationResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Htdjxu3kvZfKeh9gUiNlmZyPGeBnblyjDgnB4nttZ3sxVEAUc2Smp5usk2yR1aMARZ7sRd7udhfmF+y",
	"qCL7S2rNjLO24wB75bHUTVaRVU899aH3k8yUldGovZtcvp9UwooSPVr+3zdW6Cx/Jkqk/0l0mVWVV0ZP",
	"Lievc4Q1fw9alLiYpBNFn1fC55N0ovml8E86sfi2Vhbl5NLbGtOJy3IsBS3q9xU957xVeju5vb2lh11l",
	"tMMggpAv8W2NztP/MqM9av5TVFWhMkHSnL1xJNL73rL/3+Jmcjn5f2edemfhW3f2rbXGhq2OVbJhM9gJ",
	"B6UoNsaWKBeT23TyxOhNobLPJAftYNW6po/oP7y1g53yOXj6vrYWtYccRRDvqbFrJSXqzyOfq9dvMPNQ",
	"iOzasUTNHUMmKrFWhfL7BbCVGLmHTFirkJ9c6uZlJcEZEBpMhVZ4YyETGrZWaA/Kgwqaqy1MjV4bYaXS",
	"29liqUnfZ8Y/NbWWn17dZwZcneWNtZOUhVAln/pPWtQ+N1b9ip9Bkse1z1H7uCoo1x26sbARqmBbvW0c",
	"rOfEP6jgQZWls/YqeFdQKfytPJbuPtHCYq/qshR2TwcQ/VdYK/aT4L2Nq/+jW/6X9kHDN09vDpc6Eo0M",
	"exx14hnPhZQWnUPJThAuBZQkJDpAlQaOjuFmKG9EK956TOQnPad8ia4u/LiElr8DswExdGRvhXYi479/",
	"+7f/Zr9R0sE0F1oW6Gb0Dn0oqgq1xKiVI52Gx6OkO977ydHJ0OJxyVaQdtWUPMxYiZbRu7n/o8O7845J",
	"kLGzCkZ8dK3YfDyU/G91KfTcopBiXSCU6JzY4uhVRvA4XuO5hovzRykr20MYbxpEaeBkZNkDpYKUY2p9",
	"97b4lxrHDHYYOoWUiuQSxYveUyH6HYhdhec4jEp4S6tDt1hP2E6Kt40IB/gAdIJzo4s9PNlXOdqw3P0K",
	"hwVPKNyZ+lDjzBR1qYfgcY/xpBNrdiOW+9Ls5qV4Y2z0nStAkeVgzQ5EobY6Rr6448Bcmz9G9rrTcBvp",
	"o0hjuv8NReHzY8Wd2mq0p9GJ3cxYUJLQ2u/B58qB8yK7BtdqQ1rgO1FWBe0qlby8xv3lr//04/ViMW75",
	"Xvg6eFH7mrm+927ja2MKvvLGii3+IPY44qsnQLNZ58j6pKg8WqBvYYqL7QJKLI3dp7BRBbq981im4B6l",
	"UBnntxZdChrNxZvZ/QYaoZkfuk+T8VhX0Fdjpkcu43Nr6m0OXqF1KXhTwTQTWY4zwo+18d6UMI2x3guv",
	"bnA2sMK7gubglO8zyyjmmI4/o1WbGPyfMJIda/OiBQ7YGAsCbnovga27uONEieByUSHscvQEFhKzQhCb",
	"UHqp+Rk22YaEkT6yLlCeidqbUniVzYh40G2iBCHnucmInh0Gq6wwrrY45vbGt/EpPETnzTLvWVLRTzKA",
	"Nboz0Edy8Dq36HJTjFCIH8W7hkKAU78iR8H13iPfO1jkMARCS/o7Fy6HChvOBz8Iu0W71M0K5NfXqqpQ",
	"BienE54GdYQqv3Ls78KTYgwBqiggyzG7RklM9nmpfE9jQd/GlS1uhSVSwBGcJA1HG1VW2uM22FPRuO9Q",
	"0Wh2wF/DdL3nM5wFJYUEqSxmvtgvoJGCPw5coayMQ7nUtu8dNwp3fCu7XGU5lGIPpXDX/EphgqDE5kPs",
	"NRoESMSKzouFSInu80WKKFWnuvIMiqb2sC6UluAq491A5RPQ0FjXfS7zVKgiWuHQPCV6oYpRpFOnOCjb",
	"oLGNrsQzcuFbDj5imSduiVYLZ7HLkcw/R16FLIaSULN2aG9OrFkaOeJVmbG2rvycjZrvy3lDbh0+kEZ/",
	"5aEUPuNUUllgI5+6aC/W+DO6zauldlhs5jmKwsGNEjAwBrVprzcqoBwo7UXmybKVvhGFkvPGnBvYid7r",
	"aWmQBh0Jw48K34SNtZBL3TrO7ApqbbESyhI5DCaBui5DFO/pyjWIwbY9ozhhPUpO4jk2V3SfHb3Eylg/",
	"xr4qo7SfKz33qqQsIDNWhizgEIWvAMs1Stcwc8JXNqDKGllnBMH+mPSzki9jYnSMA4HVPwnocuIRQ7zB",
	"o3zMCmyMLYUn9iE8stQnMDXGmrui3Eh0uk0n0ZQfnmGOeewItVNy1F/N9YiH2ZpDnAZtGtdysCNn25ha",
	"U7RrsbvnZWtjChQ6Ei/7gWfW42rRUm2tNX3ZXcKEHjMUO8igD1KOu8w1Xki7S19CPoOHmfA4T7L83e+7",
	"sOga93GcZotjMelJpTdmhCp8++o1PH7xfaQ1TultgZAkVuhrnMt1kgS2ctlLdDn4tuluDOmELeR1wSU5",
	"3dxaUTEW7mn1crHUS/0YGHct5MZ5B/hOUKyEJDE68qIkSaEQtSZWBBtrypDtkysT320QjyP/UmsDHjXl",
	"oSS/zXJ1Q1Bbe6W3wQIRKuFzx7snyXGtR0BV1NstSywC106SiJjPDD2fwt//9XXKp3SNkT9pudT4zqN2",
	"al3gLIUsNw6J8UDL8L5yUfCr4Ah8giLzQfyNsQiV0g60WXK9C/jucQGvUEvY5cIjnVRmkRMeUfRgrbZM",
	"DUNqgO8qzLxrjmapUUsGTRfS9q50CATJRcp3Rt+sLs6/Xp2tLs4frcDUPjMlOhB0tjKcUrHUtZZoQeg9",
	"sJC0wgIex/pce4zdHvO1cChDZkkWRV4JhfBeZUhXwHTot//8d9hZ5ZH/ErJUOkku6Y4A5hAeShJglQrl",
	"PDRFrxQ2SCE2Gh/tojTTV6YraZOh0wKuWY13ShJerWfHYY3moSgEP3QYWFwKMY7PY1DW3hpHx66MTsEw",
	"0a+sulEFblGCqRwp8yS6iCWfim7z5JvnL5MkUhyXjhTegkdt0KLOmF8EQrHUSgYWHOpas1AIJrts6sCN",
	"S7pIQazY8X6Boyz1dNWvn2ZrY1czJurG55G5KqPdwMkgSbSBv796/ozC6JvwCCmwAbHUkcA/hqxQREiS",
	"7nxdAuTVgZpMX/z0ehYyDYcepi+ev3pNdgjCm1JlS90r4s1IZYdakhOTvqTCFQSmBBZ9bbWDfjpAD6SR",
	"PxMsBKvXRpMJN3hFIMSaKS2RC4GasKdDLMqbb9h2MqOdt3XmUUbg+PYG7T4IoBysKcKFq2lTqWiBiySB",
	"x0UBIssoyfCmh5NdgrM1XLUPnG+QjV3B3tRcseeCU7B2AgMo6IYZ04Rf6vAKYUzcl4whXJg2ccH5xiI2",
	"kqz3bA5KxtsVnGYJTaTSo9V0UFxMiH0DMn2yRFqQjwXfcfYSLpuJeu2dkoFcc5ntWCp6e3VxfrGifFAq",
	"R7hcK5cz3DK6k4mwMMRaQRsP+E45H1MU5bke04QjMvZJOrlB60L8Ol98vThnilKhFpWaXE4eLc4Xj4jk",
	"EexTxDvr1+O3OMIxKWQHg+pdhAtisTRpKJwxpinvBn2i5kTFUg+ZqtOicrnx0Wfp0dLcoKMUDtmc+lVs",
	"9mbi+tF8UXu7D9yXg7NULjP01iWIuK+DN7XzTe7OaaA3oDTjEii/1MF6lOc8Y/Xdt6+hPYyz96Tk7Vmw",
	"zrP3St6uFvAy8AkHKzL1VbiF1h6+l/GwvmlO9KCv+Jfz84/Wr+l1WE50yxpVWqrJYZc7SBfnX59avxX4",
	"bNBm4pce3f9S1xHkjlDTaOFjGZpP01VUdmAvZNZi6wJjE3LyC61z4loOK+D/GJeue+Ss11y+/SWdVMb5",
	"8Y5GjIGCAhP6gOcRqXyDH7AK0qwoovTY4Qhmx8ApCPls12lJCfI1+biIENX2grmBqWLvsgtch3FSaWDv",
	"/8rBuqawByFVgKkAV6+ZZF61obwNm8FhQ1xuAuhIqFXSzRZw1OFJl9oZbpaSQEpiWRl6IkkuweK881u9",
	"hb3CIqacXPxTMl498TpZB/NHR77VBa7R9tRxL2kBTylkUtrORx8dPUle/PSaxFvvQUk+JOdRyL7/MucZ",
	"deDu9uMMATr/jZH7OzyXmMLQc9t8ba00OUA6PnPQH1C4PQKLrz8aWIz0EE+ARr9ZmJmyVJ6Oe2os14VE",
	"QT65h8qiQ+1nEUzO78eF3kjF58IfeuPi/jfanj6/8M/3v9DOZAwRboAaROI6xJiu6+J61kM2tr47oY0j",
	"zsmI3PhKIBorjk6EDhR8DxEiVpkphyz2oDbkGJErNYSkBbKOmUTA4sJgraUoUXvR0rZtLazQHrFlOxSV",
	"A2VydYXWIaNbyOmkIqbIWMeIs1MOB+wo7kn4FPT6fZwIXoodrPdzJZc6Cjqt9QgZnQVqByeZXaS6lMRG",
	"UveAyP8dek5oPizq/07sOFEdjrX/ePvh7hdfrscNHOgps7Gm1dKmroec+ZggpP8LEpA+bNij3/4ZmTjj",
	"AtnD582IedT3EY9+TBvhHCl0cbfYD7jDUvfIQ2sXo7hwFfj6SOCHsqaV8G0tigZhpp37ri7Oz1cz8ot5",
	"VXvfpKIc4uNhESfSZm4qDtNLXRruNHDq1sZqSnTDm8jdoBDoiyLk0YFY9WLSYqkfEsNf1D1X/AMj+MVd",
	"jRxm5NwimWrcFXsGyP+LsA+NsD33eGhkDXfvzt7nwuWno+srb1GUbZuEKxLrwqyh84/1HlZhlRXHyS66",
	"tq3iu6JrV7+imJ0kMI2OE75twysI15D/K4qYc7OZNw8ZC7W+1man4bf/+K8QMmPNK7TcmvbuVhD/XepW",
	"YKElt3ZjIWwPjhVuM2xWfDlxprZZewLLCTiPVaxrkZFewk4U1w3HYa7NBVUNVV2EamwQZG9q0PgBUTT6",
	"6AfFUZN59POgyceJp83NB/4UVo5juX+aaDpQ4guLqdwAjrkdudeJ2EqPfVh0HfP97dviE1ULXtY61l6P",
	"Z+Aa54OTSNArawlNMNIM5m2Q+9BJkoK4Eapg+ssbcFexG5RRrt/0oCteahG6S3PNQ0NNcb4ZyuDmTZiB",
	"YvDqorrybf149dfzr8lBv/ehZupDs8gqsq9Q6aV7gqnDQOKDS0PbXJkt4MfaNx2QpW6rpA3F0M1RTbOu",
	"D5BZFJRxsqY3qjfKirPQmBFLHc42DikEuEoSbpYFArJRhUcLti7QJQnBXDwIbnvAVJulvjtNGUJtkG/2",
	"MPx6WzyYdXxYEt9OgT6Iepx/zH3vrhmE6wgzlIsvmXz89SOWVO6a3B843zRY+aybV+ncdXHIcPrYYchf",
	"2ubHtEGG2XiFNG/HRiOnGZplnCr9hGYSdzj1040Gq+pqcVQavkFNyXrTKlc6zp+1INdTOaTqUekIbGfd",
	"mOU9DYym8zxARAdTezSPyV22JAmDY1rygOlSEyzF0kjAs8xoHXOVMNHlCD8cZha9W8AzUVJqFLdRLraq",
	"0BPeH49JemG36Dk/agblYHowAsXzcJnQ7RTcUt85Bhc2H4AX93JPdi/6k6OftIVxND570nb6l/XgQdk/",
	"rs8xFPiU8fZv/6Tp/nzcate4Q+dho6zzC/iWR9Z5tiWk3Eky6LMRV8+MlUly2Q5Ahrk2lIDvQgGMzMzU",
	"ngfxkPtoFAh5gJpwnbPU2VK73OyIuSDXzni5EGc1d9fihA2ILKvLmr4DK7jFELL+G7Scng2S+Lttsa/+",
	"J7XFE4NKJyxy6LhB7T/S4I4GMno2F9LAQOlHCewrL6wnClvrZqJodTxXt4rpXn9q2hrDM9iUXMbPVmmE",
	"8G3X94YVm92qxbSUu0Q5Ztf0HLeiYpWqN4HZH4bmcaWuUAV1RY6/Opy7XrWDHAVPTMMdA9OzBTx2e50x",
	"lveHJuLIXLzWpVZliVIJj8V+AT+KPWsNwvPMT/fzPCUv+/Q52Sge0HBJSuS5HW1w7CnKx/BRoLgmh7GE",
	"4PEI3cOgmq+tf0+fiHaOjVg+hID+5RP65skf0tYa4lTi1chlhh8v0gW1efyXWVgbeHjjn4dOPubjh3Hl",
	"7H3Q/PvQTJLII6BjU/tVQAA+rf4KV0PnCOfIDdxVGARd0R88ULoaMdwRszXVkdV+NlC/g2IwOgT9/iw1",
	"nnhtDzGMdJxevO7uNIy48k9JKlMUUGuviu6SlSO8DTPEq9lDbvo79F/eRY9E7j/Nbedm9+DbPih0Pegg",
	"Tve3GhD5wDocic/zzEGI2haTy8kZ19KiyGO/i2OgaaajD0YAm6pZXzQhR0qOTw7nWIkwNMv0Xg/9guP3",
	"fw7F84bJ868ZrPL7+MsWYX3Kk7dpM1AWilOEI8dsrLdfvKLjDZ+z7wTWUwqlvVD9Kl+Y9O0lyj3JulHb",
	"3kYx1bj95fZ/AgAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
