// Code generated by schemaf codegen. DO NOT EDIT.
// Regenerate with: ./schemaf.sh codegen

package api

import schemafapi "github.com/flocko-motion/schemaf/api"

// Provider registers all API endpoints with the schemaf framework.
// Wire up in go/main.go: app.AddApi(api.Provider)
func Provider() {
	schemafapi.Register(schemafapi.NewRawRoute(CreateNodeEndpoint{}, "Creates a graph node.", "L0 sources use multipart form upload; L1/L2 use JSON.\nL0 root creation is idempotent via content_sha256."))
	schemafapi.Register(schemafapi.NewRoute[CreateRunReq, CreateRunResp](CreateRunEndpoint{}, "Registers a new worker run and returns a run_id.", ""))
	schemafapi.Register(schemafapi.NewRoute[GetEdgeReq, EdgeResponse](GetEdgeEndpoint{}, "Returns an edge by ID with its metadata.", ""))
	schemafapi.Register(schemafapi.NewRoute[GetEdgeProvenanceReq, EdgeProvenanceResp](GetEdgeProvenanceEndpoint{}, "Returns the provenance context of an edge: run, worker config node.", ""))
	schemafapi.Register(schemafapi.NewRoute[GetEntityReq, GetEntityResp](GetEntityEndpoint{}, "Returns an entity with all its relations, sorted by temporal validity.", ""))
	schemafapi.Register(schemafapi.NewRoute[GetEntityTimelineReq, GetEntityTimelineResp](GetEntityTimelineEndpoint{}, "Returns all relations of an entity sorted chronologically by valid_from.", ""))
	schemafapi.Register(schemafapi.NewRawRoute(GetNodeContentEndpoint{}, "Returns the raw content bytes of a node.", "Serves from Postgres cache if available, otherwise proxies from S3."))
	schemafapi.Register(schemafapi.NewRoute[GetNodeEdgesReq, GetNodeEdgesResp](GetNodeEdgesEndpoint{}, "Returns edges connected to a node, filterable by direction and type.", ""))
	schemafapi.Register(schemafapi.NewRoute[GetNodeReq, NodeResponse](GetNodeEndpoint{}, "Returns a node by ID with full metadata and inline content.", ""))
	schemafapi.Register(schemafapi.NewRoute[GetNodeProvenanceReq, ProvenanceSubgraph](GetNodeProvenanceEndpoint{}, "Returns the upstream provenance chain from a node back to L0 roots.", ""))
	schemafapi.Register(schemafapi.NewRoute[GetQueueReq, GetQueueResp](GetQueueEndpoint{}, "Returns unprocessed nodes for a given worker type.", ""))
	schemafapi.Register(schemafapi.NewRoute[GetRunReq, GetRunResp](GetRunEndpoint{}, "Returns run details and all nodes created in that run (with cascading derivatives).", ""))
	schemafapi.Register(schemafapi.NewRoute[ListEdgesReq, ListEdgesResp](ListEdgesEndpoint{}, "Returns edges with optional type filter.", ""))
	schemafapi.Register(schemafapi.NewRoute[ListNodesReq, ListNodesResp](ListNodesEndpoint{}, "Returns a filtered, paginated list of nodes.", ""))
	schemafapi.Register(schemafapi.NewRoute[ListRelationsReq, ListRelationsResp](ListRelationsEndpoint{}, "Returns filtered relation nodes.", ""))
	schemafapi.Register(schemafapi.NewRoute[PurgeRunReq, PurgeRunResp](PurgeRunEndpoint{}, "Deletes all edges and nodes created in a run, cascading", "to any nodes derived from them. L0 root nodes are never deleted."))
	schemafapi.Register(schemafapi.NewRoute[SearchEntitiesReq, SearchEntitiesResp](SearchEntitiesEndpoint{}, "Searches entities by full-text query over names and aliases.", ""))
}
